### ISSUE TITLE
Null safety error

### ISSUE THREAD

**Issue by orliu** [Codelessly/ResponsiveFramework#100]
dependencie version:  
responsive_framework: ^0.1.8

../../../Library/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/responsive_framework-0.1.8/lib/responsive_wrapper.dart:622:29: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Library/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addObserver(this);
                            ^^^^^^^^^^^
../../../Library/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/responsive_framework-0.1.8/lib/responsive_wrapper.dart:623:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Library/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^
../../../Library/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/responsive_framework-0.1.8/lib/responsive_wrapper.dart:635:29: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Library/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.removeObserver(this);
                            ^^^^^^^^^^^^^^
../../../Library/Android/flutter/.pub-cache/hosted/pub.flutter-io.cn/responsive_framework-0.1.8/lib/responsive_wrapper.dart:645:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Library/Android/flutter/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {

**Comment by orliu** [comment]
I download the 0.1.8 source code, that is WidgetsBinding.instance!...., seems ok!  but when i exec flutter pub get, in the pub cache file .pub-cache/hosted/pub.flutter-io.cn/responsive_framework-0.1.8/lib/responsive_wrapper.dart:645:29,  ,  WidgetsBinding.instance.., seems error, i don't know what happend.

**Comment by rlaheri99** [comment]
**Same Issue with**
Flutter version 2.10.4
Dart version 2.16.2

responsive_framework: ^0.1.5

**Comment by sleewok** [comment]
Try updating to flutter 3

**Comment by orliu** [comment]
> 

Thanks sellwok!
