### ISSUE TITLE
Null error

### ISSUE THREAD

**Issue by rajeshkumaradam666** [Codelessly/ResponsiveFramework#102]
/G:/flutter2.10.5/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.8/lib/responsive_wrapper.dart:622:29: Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/G:/flutter2.10.5/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addObserver(this);
                            ^^^^^^^^^^^
/G:/flutter2.10.5/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.8/lib/responsive_wrapper.dart:623:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/G:/flutter2.10.5/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^
/G:/flutter2.10.5/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.8/lib/responsive_wrapper.dart:635:29: Error: Method 'removeObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/G:/flutter2.10.5/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.removeObserver(this);
                            ^^^^^^^^^^^^^^
/G:/flutter2.10.5/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.8/lib/responsive_wrapper.dart:645:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('/G:/flutter2.10.5/packages/flutter/lib/src/widgets/binding.dart').
Try calling using ?. instead.
    WidgetsBinding.instance.addPostFrameCallback((_) {
                            ^^^^^^^^^^^^^^^^^^^^

FAILURE: Build failed with an exception.

* Where:
Script 'G:\flutter2.10.5\packages\flutter_tools\gradle\flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'G:\flutter2.10.5\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 16s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by sleewok** [comment]
I updated to flutter 3 and this issues went away for me.

**Comment by searchy2** [comment]
I've released a v0.1.9 as a compatibility release for Flutter v2.
Once you migrate to Flutter v3, please use v0.2.0.
