### ISSUE TITLE
How to use with Listview.builder?

### ISSUE THREAD

**Issue by sleewok** [Codelessly/ResponsiveFramework#103]
It is pretty straightforward to use ResponsiveRowColumn on standard widgets. 

However, I am struggling to figure out how to get the responsive_framework to work with the Listview.builder to get responsive rows/columns. Any help would be greatly appreciated!

**Comment by sleewok** [comment]
For anyone looking at this. Use the ResponsiveGridView.builder.

**Comment by searchy2** [comment]
Great! Hope it works for you. 

Otherwise, share your ideas for what you need.
