### ISSUE TITLE
Get Render Object Position/Offset is not Match with UI

### ISSUE THREAD

**Issue by irufano** [Codelessly/ResponsiveFramework#104]
## Step to reproduce:
- add global key in widget (in this case I use icon bell)
- call this in some function to get offset of the widget
```dart
 RenderBox? box =
        key.currentContext?.findRenderObject() as RenderBox?;
 Offset? position = box?.localToGlobal(Offset.zero);
 ```
 - showing custompaint based on current offset of the widget
 
## Actual Result: 
the draw paint not match with the current UI/widget,
<img width="348" alt="Screen Shot 2022-05-25 at 18 40 42" src="https://user-images.githubusercontent.com/41888110/170253820-59fdd51e-b049-4fb9-939d-9a581a653a37.png">

## Expected Result:
the draw paint should match with the current UI/widget,

**Comment by egonbeermat** [comment]
Having the same issue as above, the position returned is in the original co-ordinate system, not the scaled co-ordinates. Are there any known workarounds or methods to translate?
