### ISSUE TITLE
maxWidth and page navigation animation (flutter web 2 & 3)

### ISSUE THREAD

**Issue by knbmedia** [Codelessly/ResponsiveFramework#105]
Hi
In my Flutter Web application I set the max width of my app to 800 pixels.
```
builder: (context, widget) => ResponsiveWrapper.builder(
          ClampingScrollWrapper.builder(context, widget!),
          maxWidth: 800,
          minWidth: 600,
          defaultScale: true,
          breakpoints: [
            ResponsiveBreakpoint.resize(480, name: MOBILE),
            ResponsiveBreakpoint.autoScale(800, name: TABLET),
            ResponsiveBreakpoint.resize(1000, name: DESKTOP),
          ],
          background: Container(color: Color(0xFFccF5F5))),
```
But when pushing new page, the default slide transition start (or end when back) outside this limit:

![transition](https://user-images.githubusercontent.com/1955646/171850822-5617aa25-02e6-4a19-9f08-efea2bfb856a.gif)

To reproduce, juste create a default flutter project, use this package with maxWidth and navigate to a second page.

Regards

**Comment by searchy2** [comment]
I recommend overriding the mobile swipe transition for Flutter Web.
Please see the example in the examples folder for overriding the navigator transition.

**Comment by searchy2** [comment]
Closing issue with the above solution. Feel free to reopen.
