### ISSUE TITLE
Code structuring with Provider and GetIt packages

### ISSUE THREAD

**Issue by remsysinc** [Codelessly/ResponsiveFramework#106]
Love the idea of this package!  Coming from a Bootstrap environment on web to mobile, this concept is very appealing.

I'm using the Provider and GetIt packages and am having trouble configuring the main.dart code structure to integrate this package.  My code is as follows and I'd like to see an example of how you'd add your package.  I feel this inquiry could help a lot of people as Provider and GetIt seem to be extremely popular:

  // This widget is the root of your application.
  // Where/how to inject/add the ResponsiveFramework?
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => LoginViewModel()),
        ChangeNotifierProvider(create: (_) => HomeViewModel()),
        ChangeNotifierProvider(create: (_) => TestViewModel()),
        StreamProvider<InternetConnectionStatus>(
            initialData: InternetConnectionStatus.connected,
            create: (_) => InternetConnectionChecker().onStatusChange),
      ],
      builder: (context, child) {
        return GetMaterialApp(
          theme: ThemeData(
            brightness: Brightness.light,
            primaryColor: Colors.purple[800],
            secondaryHeaderColor: Colors.cyan[600],
            fontFamily: 'Verdana',
            textTheme: const TextTheme(
              headline1: TextStyle(fontSize: 50, fontWeight: FontWeight.bold),
              headline6: TextStyle(fontSize: 30.0, fontStyle: FontStyle.italic),
              bodyText2: TextStyle(fontSize: 18.0, fontFamily: 'Hind'),
            ),
          ),
          debugShowCheckedModeBanner: false,
          title: "My App",
          home: WelcomeView(),
        );
      },
    );
  }

Any assistance is greatly appreciated!  Thank you.

**Comment by gOzaru** [comment]
Dude, you should check on the [closed issue here](https://github.com/Codelessly/ResponsiveFramework/issues/44#issuecomment-789415784), before creating a new issue. It answered your question.
