### ISSUE TITLE
Using Flutter Inspector > Toggle select widget mode will restart the app

### ISSUE THREAD

**Issue by itsJoKr** [Codelessly/ResponsiveFramework#115]
I've noticed in my app with ResponsiveFramework that whenever I click on `Flutter Inspector > Toggle select widget mode` it will route me back to the first screen. There is no error of any kind. When I remove ResponsiveFramework everything works.

I can say that problem might be in wrappers in `MaterialApp build` because my other wrapper behaves

I also have a few wrappers in `MaterialApp builder` method and noticed they work in a weird way with RespnsiveFramework. I guess inspector also works as a wrapper.

To recreate: 
1. Run the example project in Chrome
2. Click on some button to push any page 
3. Click on `Flutter Inspector > Toggle select widget mode`

Expected:
Toggle select widget mode is active

Actual:
The screen is reset to first screen.

**Comment by itsJoKr** [comment]
Noticed that the probable issue is FittedBox which is inserted into the tree. I ended up rebuilding my own solution.

**Comment by pppshiwen** [comment]
same question
