### ISSUE TITLE
[Question] What would be the best way to configure the theme?

### ISSUE THREAD

**Issue by MdeBruin93** [Codelessly/ResponsiveFramework#116]
Hello,

I'm giving this framework a try, so far I think it's amazing, however, I'm missing the Theme property on the ResponsiveWrapper object.
Currently using the ResponsiveWrapper.builder constructor, but can't find any parameter for the ThemeData.

**Comment by jan-koz** [comment]
You should have ThemeData under MaterialApp widget, not ResponsiveWrapper.builder
