### ISSUE TITLE
How to integrate this responsive framework with go router package

### ISSUE THREAD

**Issue by moshOntong-IT** [Codelessly/ResponsiveFramework#117]
I am using a go router package to enhance my router to my flutter project. This is how I implement the responsive framework in go router
```
routes: [
      ShellRoute(
        builder: (context, state, child) => ResponsiveWrapper.builder(
          ClampingScrollWrapper.builder(context, child),
          maxWidth: 1200,
          minWidth: 480,
          breakpoints: const [
            ResponsiveBreakpoint.resize(480, name: MOBILE),
            ResponsiveBreakpoint.autoScale(600, name: TABLET),
            ResponsiveBreakpoint.resize(1000, name: DESKTOP),
            ResponsiveBreakpoint.autoScale(2460, name: '4K')
          ],
        ),
        routes: [
          GoRoute(
            path: APP_PAGE.home.toPath,
            name: APP_PAGE.home.toName,
            builder: (_, __) => RootPage(),
          ),
          GoRoute(
            path: APP_PAGE.splash.toPath,
            name: APP_PAGE.splash.toName,
            builder: (context, state) => SplashPage(),
          ),
          GoRoute(
            path: APP_PAGE.login.toPath,
            name: APP_PAGE.login.toName,

            // TODO add login page
            builder: (context, state) => SizedBox.shrink(),
          ),
          GoRoute(
            path: APP_PAGE.game.toPath,
            name: APP_PAGE.game.toName,
            builder: (context, state) {
              final questGameKey = state.params['questGameKey'] ?? 'unknown';
              return GamePage(questGameKey: questGameKey);
            },
          ),
        ],
      ),
    ],
```

The problem will occur when I used a Responsive condition it said there:
"A responsive condition was caught referencing a nonexistent breakpoint. A ResponsiveCondition requires a parent ResponsiveWrapper or remove breakpoint references." 

Excpected: The responsive condition must be working because I already use the ResponsiveWrapper in my go router builder.

**Comment by searchy2** [comment]
This is interesting! 
I'm not familiar with ShellRoute, is that the new nested navigation API the go_router team implemented? 
I've been meaning to learn more, haven't got around yet.

**Comment by Ernest-Novvia** [comment]
@moshOntong-IT Did you find a solution? Was aboout integrating responsive framework with go_router in a new project.

**Comment by moshOntong-IT** [comment]
> @moshOntong-IT Did you find a solution? Was aboout integrating responsive framework with go_router in a new project.

Yeah I did

This is how I solve the problem
`BlackboltWidget(
        title: 'One sound, One word',
        routerConfig: goRouter,
        builder: (context, child) => ResponsiveWrapper.builder(
          ClampingScrollWrapper.builder(context, child!),
          maxWidth: 1200,
          minWidth: 480,
          breakpoints: const [
            ResponsiveBreakpoint.resize(480, name: MOBILE),
            ResponsiveBreakpoint.autoScale(600, name: TABLET),
            ResponsiveBreakpoint.resize(1000, name: DESKTOP),
            ResponsiveBreakpoint.autoScale(2460, name: '4K')
          ],
        ),
      ),`

**Comment by Ernest-Novvia** [comment]
@moshOntong-IT What is BlackboltWidget?

**Comment by moshOntong-IT** [comment]
> @moshOntong-IT What is BlackboltWidget?

Heheh dont worry Blackbolt Widget just a extend of Material Widget. It is my custom widget
