### ISSUE TITLE
How to show drawer on mobile and tablet and not on desktop?

### ISSUE THREAD

**Issue by NTMS2017** [Codelessly/ResponsiveFramework#118]
Hi,

I got headache last 2 days for working responsive_framework. I download all the example that shows in pub.dev and couldn't make it to work correctly.

In flutter.dev examples the drawer is not working on web. iOS version didn't run. I still believe is better than others but I am having difficulty to grasp the drawer section.

Web version I need to show open drawer (or similar) menu but on mobile and tablet I need to show menu icon so user can press and open the side menu. How to I do that? Where I can get working examples for this?

Kind Regards

**Comment by usama-karim** [comment]
There are many properties available for `ResponsiveWrapper`. Use it to know when your specified breakpoint executed.
For Example,
`ResponsiveWrapper.of(context).isMobile; // returns true or false`
