### ISSUE TITLE
ResponsiveValue.value should non-nullable

### ISSUE THREAD

**Issue by tjarvstrand** [Codelessly/ResponsiveFramework#119]
When you create a `ResponsiveValue`, you have to give it a default value, so why is `ResponsiveValue.value` nullable?

**Comment by searchy2** [comment]
Good question! The default value can be null to support passing nulls. 
An API improvement would be eliminating the required initial value perhaps?

**Comment by tjarvstrand** [comment]
> Good question! The default value can be null to support passing nulls.
An API improvement would be eliminating the required initial value perhaps?

IMHO it would be better to remove the mandatory nullability of `value`. If you really do want it to be nullable you can still have that by using eg. `ResponsiveValue<int?>` instead of `ResponsiveValue<int>` , then `value` will also be nullable

**Comment by searchy2** [comment]
Yes! This library actually predates null safety so <int?> wasn't an option.
That seems like a good implementation.

**Comment by rayliverified** [comment]
Really interesting API signature decisions.

https://github.com/Codelessly/ResponsiveFramework/pull/123#issuecomment-1592412698
