### ISSUE TITLE
Is there a conflict between responsive_framework and flutter_screenutil? 

### ISSUE THREAD

**Issue by yoer** [Codelessly/ResponsiveFramework#128]
My app runs on mobile, and uses both responsive_framework and flutter_screenutil.

In the app, there are two different designSize values for flutter_screenutil in two widgets (home page and live page). 

when switching back from the screen with a different designSize (**live page**), 
I reset the previous screen's (**home page**) designSize using ScreenUtil.init. 

However, some elements in certain areas(user id part) of the **home page** interface are partially reduced in size.
![img_v2_e8c5de3f-5ba8-4e46-bfea-2c88f2f481ag](https://user-images.githubusercontent.com/11307627/230325104-6b0bac5d-82ba-4268-a184-8e077757a92e.jpg)
![img_v2_5b324784-dccb-44d7-b792-bb3f764d2fbg](https://user-images.githubusercontent.com/11307627/230325084-7687e0c7-dc7f-48e2-8efd-acfb42ab28e4.jpg)

I suspect that some of the size judgments in responsive_framework may have been affected.
Is there a method in responsive_framework similar to ScreenUtil.init for resetting the screen size?

App:

``` dart
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      useInheritedMediaQuery: true,
      rebuildFactor: RebuildFactors.all,
      designSize: Size(390, 844),
      builder: (context, child) => MaterialApp(
        builder: (context, widget) => ResponsiveWrapper.builder(
          widget,
          maxWidth: 1200,
          minWidth: 428,
          defaultScale: true,
          breakpoints: [
            const ResponsiveBreakpoint.resize(428, name: MOBILE),
            const ResponsiveBreakpoint.autoScale(800, name: TABLET),
            const ResponsiveBreakpoint.resize(1000, name: DESKTOP),
          ],
        ),
        home: HomePage(),
      );
  }
``` 

HomePage -> LivePage

LivePage:

``` dart
  @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
          designSize: const Size(750, 1334),
          minTextAdapt: true,
          splitScreenMode: true,
          builder: (context, child) {
            return Container();
          },
        );
  }
        
  @override
  void dispose() {
    super.dispose();
  
   ScreenUtil.init(...);
 }
```

**Comment by rayliverified** [comment]
Can you try changing the context variable? I suspect the name shadowing might be passing the wrong context without the updated MediaQuery from ScreenUtils to the ResponsiveWrapper.

```dart
 @override
  Widget build(BuildContext context) {
    return ScreenUtilInit(
      useInheritedMediaQuery: true,
      rebuildFactor: RebuildFactors.all,
      designSize: Size(390, 844),
      builder: (context, child) => MaterialApp(
        builder: (context2, widget) => ResponsiveWrapper.builder(
          widget,
          maxWidth: 1200,
          minWidth: 428,
          defaultScale: true,
          breakpoints: [
            const ResponsiveBreakpoint.resize(428, name: MOBILE),
            const ResponsiveBreakpoint.autoScale(800, name: TABLET),
            const ResponsiveBreakpoint.resize(1000, name: DESKTOP),
          ],
        ),
        home: HomePage(),
      );
  }
```
