### ISSUE TITLE
Discussion Thread

### ISSUE THREAD

**Issue by searchy2** [Codelessly/ResponsiveFramework#13]
Discuss the Responsive Framework here ⬇️

Feel free to leave your thought on the features, API, and functionality. Or use this to start a discussion and share what's on your mind.

**Comment by visual-velocity** [comment]
Hi,Your library is very well designed,So can you tell/suggest us that is it working fine with the device preview library, can be used to test the different size screen.

**Comment by searchy2** [comment]
I tested with FlutterDevicePreview a few months ago. There was a major release and I haven't tested with the latest yet. 
If you give it a try, let me know how it works!

**Comment by bounty1342** [comment]
Very good combo 👍  :

``` dart
          MaterialApp(
            locale: DevicePreview.of(context).locale,
            debugShowCheckedModeBanner: false,
            title: 'Title',
            theme: themeService.getTheme(),
            darkTheme: themeService.getThemeDark(),
            themeMode:
                MediaQuery.of(context).platformBrightness == Brightness.dark
                    ? ThemeMode.dark
                    : ThemeMode.light,
            builder: (BuildContext context, Widget widget) =>
                DevicePreview.appBuilder(
              context,
              MediaQuery(
                data: MediaQuery.of(context).copyWith(textScaleFactor: 1.0),
                child: ResponsiveWrapper.builder(MainView()),
                  maxWidth: 2460,
                  minWidth: 480,
                  defaultScale: true,
                  breakpoints: <ResponsiveBreakpoint>[
                    const ResponsiveBreakpoint.resize(480, name: MOBILE),
                    const ResponsiveBreakpoint.autoScale(600, name: TABLET),
                    const ResponsiveBreakpoint.autoScale(1000,
                        name: TABLET, scaleFactor: 1.2),
                    const ResponsiveBreakpoint.resize(1200, name: DESKTOP),
                    const ResponsiveBreakpoint.autoScale(2460, name: '4K'),
                  ],
                  background: Container(color: const Color(0xFFF5F5F5)),
                ),
              ),
            ),
          ),
```

You should give it a try.

**Comment by searchy2** [comment]
Glad to hear it works! 
Thanks for sharing your results.

**Comment by visual-velocity** [comment]
First of all thank Thank you very much this library. MInd blowing and beneficial framework for all of us. Hats off to you!!! You library help to my production app and reduce lots of boilerplates code

**Comment by Prn-Ice** [comment]
Hi, does this plugin help with scaling between devices of similar screen sizes eg two mobile phones with different sizes/aspect ratios, by default on flutter, a view on the target device can display just fine but on a smaller device, you could get RenderFlex errors.

**Comment by Prn-Ice** [comment]
Also, amazing presentation of this package, one of the best I've seen. I gave it a like before I even read through the whole readme.

**Comment by searchy2** [comment]
Until I can resolve the TextForm keyboard focus issue and the SafeArea issue, I cannot recommend using this library on Mobile. Yes, the scaling will adjust for smaller devices but there are framework level interactions that are not accounted for such as Overlays, TextFields, and SafeAreas.

The ResponsiveFramework works almost perfectly for Flutter Websites. 

Thanks for the kind words!

**Comment by gcostaapps** [comment]
@bounty1342, the returning MediaQuery that you use, what is it purpose? Does it change the MediaQuery parameters?

**Comment by bounty1342** [comment]
@gcostaapps it's to fix the MediaQuery for the whole app. In this case textScaleFactor is overridden.

**Comment by gcostaapps** [comment]
@bounty1342 that's great! Maybe that could be a fix for #17, because these libs generally take the MediaQuery parameters to calculate positions.

**Comment by searchy2** [comment]
Closing and migrating to https://github.com/Codelessly/ResponsiveFramework/discussions/35

**Comment by kleinpetr** [comment]
Hi I like the concept of scaling but I can't understand the scaling mechanism so lets try this one
```
ResponsiveBreakpoint.autoScale(
              260,
              name: MOBILE,
              scaleFactor: 0.5,
            ), //260-450=scale from 260 or 450?
            ResponsiveBreakpoint.resize(450, name: MOBILE), //450-800=resize
            ResponsiveBreakpoint.autoScale(
              800,
              name: TABLET,
            ),
```

the scaleFactor is calculated from the 260 version or 450 version?
Because it looks like the scale fits always the bottom version but the first breakpoint is 260 so it probably means that 0-260 is resize (by default) BUT the website with 259px width looks different then 260 so I am little bit confused because can't definitely say where the concrete layout comes in.

**Comment by searchy2** [comment]
Good question! You've got the basic understanding down but there's a bit of special behavior with how the 0 - X breakpoint works.

It doesn't makes sense to have a breakpoint scale from 0 so the first breakpoint actually inherits down.
To get the 0-260 to autoscale, the parameter you're missing is `defaultScale = true`.

For a bird's eye view of the behavior at each breakpoint segment, set `debugLog = true` to print out a visualization of the behaviors!

**Comment by adnan-haider007** [comment]
@rayliverified hi. i have a question that there is no docs update regarding new implementation in readme file also there is no details regarding device in landscape mode so what are the values need to be put in it, so it can adjust in there,kindly look into this as well,
