### ISSUE TITLE
How to use responsive_framework 1.0.0 with MaterialApp.router()

### ISSUE THREAD

**Issue by Arnooodles** [Codelessly/ResponsiveFramework#131]
I'm trying to use the `responsive framework v1.0.0` in my Flutter app, but I'm not sure how to apply it to `MaterialApp.router()` (I'm using go_router). Could you please show me an example of how to do that? I've read the documentation, but I'm still confused about some details especially with `ResponsiveScaledBox` & `MaxWidthBox`

**Comment by aliaktas-tr** [comment]
+1

**Comment by rayliverified** [comment]
Good question! 

If you're using MaterialApp.router(), you can pass in the ResponsiveBreakpoints.builder() into the builder parameter of `router()`. Much like with a regular MaterialApp.

![snap_screen_20230426005154](https://user-images.githubusercontent.com/19896174/234481818-ec0c3616-b4fb-4ed6-b56c-5027d9247975.png)

**Comment by Arnooodles** [comment]
Actually, I've already tried implementing your suggestion. But I think I need to use `ResponsiveScaledBox` or `MaxWidthBox` somewhere, but I'm not sure where to put them. Here's a screenshot of how the UI looks like in v0.2.0 and v1.0.0:

![image](https://user-images.githubusercontent.com/32187162/234937340-c78012be-a9e5-4ff5-a88e-42e639799da4.png)

**Comment by AdamBridges** [comment]
Is it possible to wrap the child parameter with `ResponsiveScaledBox` like so:

```
ResponsiveBreakpoints.builder(
 child: ResponsiveScaledBox(
  child: child!
 )
)
```
While the documentation does explain a bit that `ResponsiveScaledBox` is now autoScale, it would be nice if the documentation also included how resize is being handled. `MaxWidthBox` I assume?

**Comment by Arnooodles** [comment]
I tried this but encountered an error(`'ResponsiveValue requires a parent ResponsiveWrapper to reference breakpoints. Add a ResponsiveWrapper or remove breakpoint references.`). This happened when I tried to set the width for the `ResponsiveScaledBox` using `ResponsiveValue`.

Also are there any examples of how to implement the `autoScale`, `autoScaleDown`, and `resize` in v1.0.0

**Comment by A7MeDG0L0L** [comment]
> I tried this but encountered an error(`'ResponsiveValue requires a parent ResponsiveWrapper to reference breakpoints. Add a ResponsiveWrapper or remove breakpoint references.`). This happened when I tried to set the width for the `ResponsiveScaledBox` using `ResponsiveValue`.
> 
> Also are there any examples of how to implement the `autoScale`, `autoScaleDown`, and `resize` in v1.0.0

Same...
DId u find a solution ?

**Comment by Arnooodles** [comment]
> > I tried this but encountered an error(`'ResponsiveValue requires a parent ResponsiveWrapper to reference breakpoints. Add a ResponsiveWrapper or remove breakpoint references.`). This happened when I tried to set the width for the `ResponsiveScaledBox` using `ResponsiveValue`.
> > Also are there any examples of how to implement the `autoScale`, `autoScaleDown`, and `resize` in v1.0.0
> 
> Same... DId u find a solution ?

Not yet...I'm still using `v0.2.0`

**Comment by MostafaSolimanMO** [comment]
Any update on this?

**Comment by Tumist76** [comment]
Bumping this with a following problem. I'm conditionally building routes based on screen size in router. Router is used higher in the tree than `ResponsiveBreakpoints.builder` so I'm getting error:

```
FlutterError (ResponsiveBreakpoints.of() called with a context that does not contain ResponsiveBreakpoints.
No Responsive ancestor could be found starting from the context that was passed to ResponsiveBreakpoints.of(). Place a ResponsiveBreakpoints at the root of the app or supply a ResponsiveBreakpoints.builder.
The context used was: MyApp
```

My code:

```dart
void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp.router(
      title: 'Flutter Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      routerConfig: buildRouter(context),
      builder: (context, child) {
        return ResponsiveBreakpoints.builder(
          child: child!,
          breakpoints: [
            const Breakpoint(start: 0, end: 450, name: MOBILE),
            const Breakpoint(start: 451, end: 800, name: TABLET),
            const Breakpoint(start: 801, end: double.infinity, name: DESKTOP),
          ],
        );
      },
    );
  }
}

GoRouter buildRouter(BuildContext context) {
  return GoRouter(
    routes: [..._buildArticlesRoutes(context)],
  );
}

List<GoRoute> _buildArticlesRoutes(BuildContext context) {
  return [
    if (ResponsiveBreakpoints.of(context).largerThan(MOBILE)) ...[
      GoRoute(
        path: Routes.articleDetails.path,
        name: Routes.articleDetails.name,
        pageBuilder: (context, state) {
          return ArticlesMasterDetailPage.routeBuilder(
            context,
            hasDetail: true,
          );
        },
      ),
      GoRoute(
        path: Routes.articleList.path,
        name: Routes.articleList.name,
        pageBuilder: (context, state) {
          return ArticlesMasterDetailPage.routeBuilder(
            context,
            hasDetail: true,
          );
        },
      ),
    ],
    if (!ResponsiveBreakpoints.of(context).largerThan(MOBILE))
      GoRoute(
          path: Routes.articleList.path,
          name: Routes.articleList.name,
          pageBuilder: (context, state) {
            return ArticlesListPage.routeBuilder(context);
          },
          routes: [
            GoRoute(
              path: Routes.articleDetails.path,
              name: Routes.articleDetails.name,
              pageBuilder: (context, state) {
                return ArticlesListPage.routeBuilder(context);
              },
            ),
          ]),
  ];
}

```

**Comment by rayliverified** [comment]
Migration guide is up! 

https://github.com/Codelessly/ResponsiveFramework/blob/master/migration_0.2.0_to_1.0.0.md

**Comment by jlin5** [comment]
@rayliverified In the migration guide can you mention how to use **ResponsiveScaledBox** with **MaterialApp.router** without it throwing an error? A workaround I found is to wrap **ResponsiveScaledBox** in a **Builder** widget.

```
        return MaterialApp.router(
          routerConfig: routingController.router,
          builder: (context, child) => ResponsiveBreakpoints.builder(
            child: Builder(
              builder: (context) {
                return ResponsiveScaledBox(
                  width: ResponsiveValue<double>(
                    context,
                    conditionalValues: [
                      Condition.equals(name: MOBILE, value: 450),
                      Condition.between(start: 800, end: 1100, value: 800),
                      Condition.between(start: 1000, end: 1200, value: 700),
                    ],
                  ).value,
                  child: child!,
                );
              },
            ),
            breakpoints: [
              const Breakpoint(start: 0, end: 450, name: MOBILE),
              const Breakpoint(start: 451, end: 800, name: TABLET),
              const Breakpoint(start: 801, end: 1920, name: DESKTOP),
              const Breakpoint(start: 1921, end: double.infinity, name: '4K'),
            ],
          ),
        );
```

Thank you for the migration guide!

**Comment by rayliverified** [comment]
Oh right, because the ResponsiveValue needs the context passed from the ResponsiveBreakpoints. 

Your solution is correct.

I'll think about adding a `builder` parameter to the ResponsiveBreakpoints.builder() that can be used instead of child.
