### ISSUE TITLE
"valueWhen" isn't defined, 

### ISSUE THREAD

**Issue by Jwise777** [Codelessly/ResponsiveFramework#139]
I believe I was able to add in the required code to my main.dart file, but once adding the required code I now get these 2 errors:
"valueWhen":
    the named parameter "valueWhen" is undefined
"ResponsiveValue" 
 The named parameter 'conditionalValues' is required, but there's no corresponding argument

I have looked at the exported files in "responsive_framework.dart" file for these 2 terms and they look like they are defined, but on all of the files of my project I have this error for these 2 terms.

Any help?

Thank you!

James

**Comment by rayliverified** [comment]
Odd, can you share a screenshot of the errors you're running into?

**Comment by Jwise777** [comment]
<img width="1920" alt="Screenshot 2023-05-09 at 1 13 04 PM (2)" src="https://github.com/Codelessly/ResponsiveFramework/assets/109560319/1601b176-5fed-440b-b7c2-8f2d7f12814c">

**Comment by Jwise777** [comment]
![Uploading Screenshot 2023-05-09 at 1.12.59 PM.png…]()

**Comment by Jwise777** [comment]
<img width="467" alt="Screenshot 2023-05-09 at 1 18 13 PM" src="https://github.com/Codelessly/ResponsiveFramework/assets/109560319/5bf5b064-0dc0-49e8-9729-32a1732fa6aa">

**Comment by Jwise777** [comment]
<img width="802" alt="Screenshot 2023-05-09 at 1 19 44 PM" src="https://github.com/Codelessly/ResponsiveFramework/assets/109560319/a018acd2-f872-4683-b684-37cdf6a9f634">

**Comment by Jwise777** [comment]
Thanks a ton!!!

**Comment by Jwise777** [comment]
One more question, what has **hiddenWhen** changed to and where could I find the documentation on these changes? Sorry, I'm knew to this

**Comment by rayliverified** [comment]
Please reopen if you have additional questions.
