### ISSUE TITLE
Overlap at status bar

### ISSUE THREAD

**Issue by theantiqa** [Codelessly/ResponsiveFramework#14]
Getting overlap at status bar.

![image](https://user-images.githubusercontent.com/46623939/85875733-4ec93800-b7f2-11ea-812f-9901a221d3f9.png)

This is setting which i set. 
![image](https://user-images.githubusercontent.com/46623939/85875993-b54e5600-b7f2-11ea-9a8d-35705bc788ae.png)

**Comment by searchy2** [comment]
Thanks for reporting this issue! 
I believe this is related to SafeArea offsets. Are you using a SafeArea in your layout?

**Comment by theantiqa** [comment]
Yes I have use SafeArea in my layout. once it fixed then this library gonna be rock.. 
Please Resolve asap. i already used in my current running app if this will not fixed then I have to move with  other library :(

**Comment by searchy2** [comment]
I'll likely have some time in 2 weeks.

**Comment by theantiqa** [comment]
So will solve it?

**Comment by searchy2** [comment]
Yes, it's on the roadmap!

**Comment by theantiqa** [comment]
Thanks

**Comment by theantiqa** [comment]
what is status?

**Comment by theantiqa** [comment]
I don't think I have to go with this plugin. you wasted my time.

Thanks

**Comment by Bilonik** [comment]
> I don't think I have to go with this plugin. you wasted my time.
> 
> 
> 
> Thanks

You know you can submit a PR. Say thanks, people like @searchy2 make plugins open source for the flutter community.

**Comment by theantiqa** [comment]
I can't get any reply regarding overlap issue from your side since many days. so that.
If you give me duration when it will be done then its good for me and then i will use it in new project.

Thanks

**Comment by searchy2** [comment]
I apologize for the delay and need to be clearer in communicating whether I'm actively developing this project. 

The good news is that the Responsive Framework is open source so you have the ability to look at the source code and contribute changes!

**Comment by searchy2** [comment]
I'll be updating the Reponsive Framework this week for the new Pub.dev so I'll be able to tackle some open issues.

**Comment by theantiqa** [comment]
Thanks for your reply. i hope i will get solution very soon. 

Thanks

**Comment by searchy2** [comment]
I've restarted work towards a stable v0.1.0 release. Targeting 100% test coverage and documentation this week!

**Comment by TusharDcs** [comment]
Thanks man.

**Comment by TusharDcs** [comment]
Hi,

I have tried your new code from github. but can't get any solution still its looking like same.
i am attaching source code as well as screen shots for 2 different different device. you can see still overlap issue. 
![image](https://user-images.githubusercontent.com/68111937/88138748-e8c2ab80-cc0b-11ea-84e9-f9221e32bb92.png)

you can see attached source code below. please guide me if i made any mistake.

[flutter_demo1 22-7-2020(1).zip](https://github.com/Codelessly/ResponsiveFramework/files/4958052/flutter_demo1.22-7-2020.1.zip)


Thanks

**Comment by searchy2** [comment]
Haven't released a new version yet. There's progress each day.

**Comment by searchy2** [comment]
Thanks for providing a demo.

**Comment by theantiqa** [comment]
Once it done let me know.

**Comment by TusharDcs** [comment]
Hi,

Have you resolved issue regarding overlap in new version 0.08?

Thanks

**Comment by searchy2** [comment]
Not yet, but this is the next issue I'm tackling!

**Comment by theantiqa** [comment]
when it will be resolved?

**Comment by sorasful** [comment]
@theantiqa you annoy me. You are not some client at some bar here. Open-sourced projects are built by people who are willing to give their time for the community.  So if you want it so badly and so quickly, just do it yourself (and don't forget to send a PR 😉 ).

**Comment by searchy2** [comment]
@sorasful I hide your comment because personal attacks are not allowed. 
Open source is a wonderful thing and software wouldn't work without people giving their time and energy to create useful libraries. 

@theantiqa, you are always welcome to contribute and I can even help point you in the right direction as to what needs to be done to fix this issue. Please realize that open source contributors try to be as helpful as time and resource constraints allow.

**Comment by searchy2** [comment]
Thanks you @TusharDcs for the sample project.

The status bar overlap is fixed in v0.0.10.
