### ISSUE TITLE
Issues with Cupertino Navigation bar

### ISSUE THREAD

**Issue by joanfortes** [Codelessly/ResponsiveFramework#15]
Hello, i'm using the default configurantions for this lib, but when i use CupertinoPageRoute and both screens have a CupertinoNavigationBar this happens:

![Bug](https://user-images.githubusercontent.com/49821124/87547418-738e2e00-c681-11ea-9dc7-8bca64847d4b.gif)

**Comment by searchy2** [comment]
Thanks for filing this issue. I've noticed that there are quite a few Cupertino related bugs. Cupertino support is planned for v0.3.0.
However, this specific issue might be fixed when I solve the SafeArea issue.

**Comment by btd1337** [comment]
@searchy2 I have the same problem here. Any prevision for this bug to be solved?

Is it possible to release it in version `0.0.8`?

**Comment by mateus96mt** [comment]
Looks like i am having the same problem with CupertinoNavigationBar.

I am Aldo using the default settings for this lib.

**Comment by joanfortes** [comment]
@searchy2 i've been testing some things with the lib, and i discover something, maybe can help you with the fix, when i disable the hero animation on the cupertinoNavigationTab it's stops the error,but it’s good to have the hero’s animation as it was meant to be
