### ISSUE TITLE
1.x migration documentation blocking Dart 3/ Flutter 3.10+ upgrades

### ISSUE THREAD

**Issue by mdmm13** [Codelessly/ResponsiveFramework#151]
**Issue**: It appears that lots of people (~50% of open issues) who successfully used 0.2 are stuck upgrading to 1.x, which now blocks Dart 3 and Flutter 3.10 dependency upgrades. It appears to be a **documentation issue** rather than a code issue, hence an easy fix.

**Request**: Clarify upgrade path documentation from 0.2 to 1.x.

**Affected issues**:  #131, #136, #142, #145, #146, #148, #150, #152

**Comment by rello86** [comment]
Any news on the above?
Thanks.

**Comment by rayliverified** [comment]
Good news is tomorrow is Labor Day so I'll finally have some time to update the docs and provide an example.
Thank you @mdmm13 for summarizing the issues!

**Comment by mdmm13** [comment]
> Good news is tomorrow is Labor Day so I'll finally have some time to update the docs and provide an example. Thank you @mdmm13 for summarizing the issues!

Thank you so much @rayliverified ! Think given the popularity of the package (~2500 likes 🚀), there will be lots of happy users if we can get 1.1.0 working as well as 0.2.0.

**Comment by mdmm13** [comment]
> Good news is tomorrow is Labor Day so I'll finally have some time to update the docs and provide an example. Thank you @mdmm13 for summarizing the issues!

Any updates on this @rayliverified?

**Comment by rayliverified** [comment]
Thank you all for your patience! 

I've created a migration guide. 
[Migration Guide](https://github.com/Codelessly/ResponsiveFramework/blob/master/migration_0.2.0_to_1.0.0.md)

Please review and I'll do my best to answer any questions.
