### ISSUE TITLE
When breakpointsLandscape is defined, it will always ignore breakpoints.

### ISSUE THREAD

**Issue by rienkvr** [Codelessly/ResponsiveFramework#158]
When you define breakpointsLandscape, breakpoints is never used.

I checked the code and saw this:

`bool get isLandscape => true`

This is the boolean that is checked to define which breakpoint to use, but it is always true.

**Comment by rayliverified** [comment]
Thanks for raising this issue. It's been fixed in the latest release. 

I forgot to close this issue.
