### ISSUE TITLE
withNoTextScaling not working in letest version

### ISSUE THREAD

**Issue by sanjaycdev** [Codelessly/ResponsiveFramework#170]
![image](https://github.com/Codelessly/ResponsiveFramework/assets/110217923/d31efddf-d66e-4bb6-9835-967857621c68)

i was trying to make my app's font size constant irrespective of device's font size. with below code . But it doesn't have any effect . Its working with older version of "ResponsiveFramework" does it have any work around for this ?.

`MediaQuery.withNoTextScaling(child:child!,),`

**Comment by rayliverified** [comment]
Thank you for reporting! 

This is a new MediaQuery property that should be added to the internal MediaQuery of the ResponsiveMediaQuery.

**Comment by rayliverified** [comment]
Hmmm, I can't reproduce. The MediaQuery no text scaling is flowing through properly. 

![image](https://github.com/Codelessly/ResponsiveFramework/assets/19896174/be0ab945-c747-4673-8c8e-917bbbde1584)


![image](https://github.com/Codelessly/ResponsiveFramework/assets/19896174/32be38a9-4878-4409-8924-3c457eba50f8)
![image](https://github.com/Codelessly/ResponsiveFramework/assets/19896174/19b036d1-ca5a-432c-a1ba-efbac18a1565)

**Comment by sanjaycdev** [comment]
ui after increasing system font size
![image](https://github.com/Codelessly/ResponsiveFramework/assets/110217923/e33c2f19-687f-4d78-a295-5015fafcb3b4)

>pubspec.yaml snap
![image](https://github.com/Codelessly/ResponsiveFramework/assets/110217923/80ba8ffb-26b9-465e-94ff-3078aca8adfb)


>This is my whole code 
![image](https://github.com/Codelessly/ResponsiveFramework/assets/110217923/19906772-994c-497e-b3ba-c48a97e03431)


![image](https://github.com/Codelessly/ResponsiveFramework/assets/110217923/e4a9c203-b1b3-4f37-bfc9-282bb157de74)

Hope you could find some issue in my code to fix the issue :)

**Comment by sanjaycdev** [comment]
its fixed , But couldn't find cause .
flutter and package was updated recently ,
Thanks .
