### ISSUE TITLE
Error null when defaultValue on ResponsiveValue not specified

### ISSUE THREAD

**Issue by Hasuki69** [Codelessly/ResponsiveFramework#171]
![image](https://github.com/Codelessly/ResponsiveFramework/assets/93316768/756317d5-f646-486e-ae97-40130cec09c7)

before upgrading to the latest version, i can ignore the defaultValue. now i should specify the defaultValue with mediaquery width or it will error null. 

i look at the code and find that you use defaultValue when the getValue is null, but you make the defaultValue nullable where its mean both can be null and cause the error when defaultValue not specified.
![image](https://github.com/Codelessly/ResponsiveFramework/assets/93316768/7da8c62f-4641-494c-89bb-9b2e5e7ff43c)

**Comment by dmacinator** [comment]
Try "ResponsiveValue<double?>" instead. Seems to fix it for me.

**Comment by Hasuki69** [comment]
> Try "ResponsiveValue<double?>" instead. Seems to fix it for me.

thanks for replying, it's work 👍
