### ISSUE TITLE
Does not work in iOS tablet 

### ISSUE THREAD

**Issue by AlmogRnD** [Codelessly/ResponsiveFramework#18]
Testing this out and I'm seeing it's not working on iOS tablet for a Flutter mobile app. Attached screenshot 
<img width="660" alt="Screen Shot 2020-09-04 at 6 20 32 PM" src="https://user-images.githubusercontent.com/169507/92255862-95669d00-eedb-11ea-8c2b-fd444eb4b784.png">

<img width="642" alt="Screen Shot 2020-09-04 at 6 20 48 PM" src="https://user-images.githubusercontent.com/169507/92255888-9c8dab00-eedb-11ea-8c66-444898ce8481.png">
<img width="686" alt="Screen Shot 2020-09-04 at 6 20 53 PM" src="https://user-images.githubusercontent.com/169507/92255891-9dbed800-eedb-11ea-83b6-f4f2cc41f842.png">

Maybe I'm missing something but here is my code from the main dart file 

```
class App extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ScopedModel<LocalDataModel>(
        model: LocalDataModel(),
        child: MaterialApp(
          onGenerateRoute: router.generateRoute,
          home: RootPage(
            auth: Auth(),
          ),
          builder: (context, widget) => ResponsiveWrapper.builder(
            BouncingScrollWrapper.builder(context, widget),
            maxWidth: 1200,
            minWidth: 450,
            defaultScale: true,
            breakpoints: [
              ResponsiveBreakpoint.resize(450, name: MOBILE),
              ResponsiveBreakpoint.autoScale(800, name: TABLET),
              ResponsiveBreakpoint.autoScale(1000, name: TABLET),
              ResponsiveBreakpoint.resize(1200, name: DESKTOP),
              ResponsiveBreakpoint.autoScale(2460, name: '4K'),
            ],
          ),
          theme: ThemeData(
            brightness: Brightness.light,
            primaryColor: Color(0XFF47525D),
            accentColor: Color(0xFF00AEEF),
            textTheme: Theme.of(context).textTheme.apply(
                  bodyColor: Color(0XFF47525D),
                  displayColor: Color(0XFF47525D),
                ),
          ),
        ));
  }
}
```

**Comment by antoniocasero** [comment]
This sounds like you are not enabling the iPad scheme on your ios project. The screenshot is an iPad running a simulator for iPhone apps.
It's not about the code.

**Comment by searchy2** [comment]
@antoniocasero is correct. The app is running in iPhone mode.
