### ISSUE TITLE
Scrolling stops working in the entire app when upgraded to 1.5.0

### ISSUE THREAD

**Issue by av153k** [Codelessly/ResponsiveFramework#185]
If I use any scroll wrapper with `dragWithMouse` as `true`, then scrolling stops working.

It was intended considering the scroll behavior was changed to inherit default behavior. I want to understand why the previous implementation was removed since it covered both cases - mouse and touch, very well.

**Comment by rayliverified** [comment]
Good catch.

It was missing the default drag device values.

Fixed in v1.5.1

**Comment by av153k** [comment]
Thank you.
