### ISSUE TITLE
backgroundColor in new MaxWidthBox not working 

### ISSUE THREAD

**Issue by nietsmmar** [Codelessly/ResponsiveFramework#188]
Since version 1.5.0 the background in MaxWidthBox is not working anymore. I always had it like `background: Container(color: Colors.white)` in the older versions.

Now I just added `Colors.white` to the `backgroundColor` attribute. But it always stays black.

As far as I see, the `backgroundColor` attribute is not at all about the color outside of the MaxWidthBox. How can I set this color now?

**Comment by satti8893** [comment]
> [@satheesh-redant](https://github.com/satheesh-redant) I did put a `ColoredBox` around it.

Do you mean we need to wrap the entrie ResponsiveBreakpoints.builder inside `ColoredBox` ?

**Comment by nietsmmar** [comment]
@satish-kumar-p no, around your child.
