### ISSUE TITLE
TextField, TextFormField and Button resizing not working in Flutter Web

### ISSUE THREAD

**Issue by franarolas** [Codelessly/ResponsiveFramework#20]
Currently the responsive framework is not resizing the TextField's, TextFormField's and Button's in Flutter Web at version ^0.0.8.
Is this a known issue? Is there any fix coming?

Thank you.

**Comment by searchy2** [comment]
Can you please provide me a sample? 
I just used the Responsive Framework last night on my website with TextFields and Buttons and they scaled perfectly,
https://codelessly.com

**Comment by franarolas** [comment]
I've the following:
![imagen](https://user-images.githubusercontent.com/42511706/92616843-ff59ba80-f2be-11ea-80dc-634fc2657b6d.png)

And if I do it smaller:
![imagen](https://user-images.githubusercontent.com/42511706/92618571-c9b5d100-f2c0-11ea-9df1-41a3027494df.png)

It doesn't resize.

ResponsiveBreakpoints:

```
builder: (context, widget) => ResponsiveWrapper.builder(
            BouncingScrollWrapper.builder(context, widget),
            maxWidth: 1440,
            defaultScale: true,
            breakpoints: [
              ResponsiveBreakpoint.resize(425, name: MOBILE),
              ResponsiveBreakpoint.resize(800, name: TABLET),
              ResponsiveBreakpoint.resize(1000, name: DESKTOP),
            ]
          )
```

**Comment by searchy2** [comment]
Can you try setting the breakpoint to autoScale?
```
ResponsiveBreakpoint.**autoScale**(425, name: MOBILE),
ResponsiveBreakpoint.resize(800, name: TABLET),
ResponsiveBreakpoint.resize(1000, name: DESKTOP),
```

**Comment by franarolas** [comment]
> 
> 
> Can you try setting the breakpoint to autoScale?
> 
> ```
> ResponsiveBreakpoint.**autoScale**(425, name: MOBILE),
> ResponsiveBreakpoint.resize(800, name: TABLET),
> ResponsiveBreakpoint.resize(1000, name: DESKTOP),
> ```

I will run some tests to exactly know what's going on and in the case that I found out that the error is coming from the responsive framework I will open a thread with a detailed description, thank you for your patience.
