### ISSUE TITLE
Blurring on AppBar

### ISSUE THREAD

**Issue by Prn-Ice** [Codelessly/ResponsiveFramework#23]
![Peek 2020-09-13 14-35](https://user-images.githubusercontent.com/48252841/93022938-a7cf8d80-f5e3-11ea-9b8f-e06e0af7193a.gif)

I hope you can notice, but the text on the appBar gets a bit blurred out at times. Is this a common effect of scaling.

**Comment by searchy2** [comment]
Can you provide a side by side screenshot?
I do not see any blur in the GIF.

Text does blur when scaled up. Please try scaling down which works a lot better.

**Comment by Prn-Ice** [comment]
>Text does blur when scaled up. Please try scaling down which works a lot better.

So basically `autoScaleDown` instead of `autoScale`.

> Can you provide a side by side screenshot

Ok

**Comment by Prn-Ice** [comment]
![image](https://user-images.githubusercontent.com/48252841/93024366-dfdbce00-f5ed-11ea-8a07-54ba629a3141.png)

![image](https://user-images.githubusercontent.com/48252841/93024388-07cb3180-f5ee-11ea-885d-d9357afbf23b.png)

**Comment by Prn-Ice** [comment]
I have a 720p display, I think that might be the issue. Zooming in fixes it.

**Comment by searchy2** [comment]
The issue appears to be resolved. Please reopen if the issue persists.
