### ISSUE TITLE
MediaQuery.of() The method 'dependOnInheritedWidgetOfExactType' was called on null.

### ISSUE THREAD

**Issue by SpencerLindemuth** [Codelessly/ResponsiveFramework#29]
I'm unfortunately not able to reproduce this error, and the stack trace from our logs is short and unhelpful, but I'm seeing this error pop up in our app at an alarmingly high rate. I call the `ResponsiveWrapper.builder` inside of the `onGenerateRoute` callback in `MaterialApp` so I can't figure out when the BuildContext would be null. Have you seen this issue before or know a direction to look? Like I said it's running flawlessly in all of my testing and I cannot reproduce.

```
Non-fatal Exception: FlutterError
NoSuchMethodError: The method 'dependOnInheritedWidgetOfExactType' was called on null. Receiver: null Tried calling: dependOnInheritedWidgetOfExactType(). Error thrown Instance of 'ErrorDescription'.
Non-fatal Exception: FlutterError

0  ???                            0x0 of + 814 (media_query.dart:814)
1  ???                            0x0 getDevicePixelRatio + 151 (responsive_wrapper.dart:151)
2  ???                            0x0 setDimensions + 395 (responsive_wrapper.dart:395)
3  ???                            0x0 <fn> + 454 (responsive_wrapper.dart:454)
4  ???                            0x0 _invokeFrameCallback + 1117 (binding.dart:1117)
5  ???                            0x0 handleDrawFrame + 1063 (binding.dart:1063)
6  ???                            0x0 _handleDrawFrame + 971 (binding.dart:971)
```

**Comment by searchy2** [comment]
Hi Spencer,
Let me take a look in the next few days.
The dependOnInheritedWidgetOfExactType error happens when an Inherited Widget is missing from the tree. My guess is that either the ResponsiveWrapper doesn't like the onGenerateRoute or MediaQuery is missing during one of the State's lifecycle calls.

**Comment by searchy2** [comment]
Can you share the code where you use the Responsive Framework? 

I just remembered the the onGeneratedRoute likely interferes with the builder. Instead using ResponsiveWrapper() directly is likely the right approach because then it can get the context directly from the parent MaterialApp.

**Comment by SpencerLindemuth** [comment]
``` dart
MaterialPageRoute route(RouteSettings settings, {isFullScreenDialog = false}) {
      var args =  settings.arguments as Map<String, dynamic> ?? {};
      
      WidgetBuilder builder = getRoutes(args)[settings.name];
      return MaterialPageRoute(
        settings: RouteSettings(name: settings.name),
        builder: (ctx) => ResponsiveWrapper.builder(
          builder(ctx),
          breakpoints: RESPONSIVE_BREAKPOINTS
        ),
        fullscreenDialog: args['isFullScreenDialog'] ?? false
      );
  }```

**Comment by SpencerLindemuth** [comment]
`onGenerateRoute` calls this function

**Comment by searchy2** [comment]
Instead of returning the building in the route function, can you use the ResponsiveWrapper non-builder version inside the widget tree?

**Comment by SpencerLindemuth** [comment]
I tested by removing the `.builder` method and returned the ResponsiveWrapper() in the above function and it worked as long as I set `shrinkwrap: false`. Is that what you mean? Or do you mean wrapping the `MaterialApp` in a ResponsiveWrapper?

**Comment by searchy2** [comment]
Yes, that's right. 
Is this the new navigator 2 you are using? I have very limited experience with Navigator 2 and need to do more experiments.

**Comment by SpencerLindemuth** [comment]
Nope still Navigator 1, just wrote a custom route table for better organization and cleaner dependency injection

**Comment by SpencerLindemuth** [comment]
Good news, I was finally able to reproduce this issue! It's happening when the app opens an external link, and I press the shortcut button in the top left corner to go back to the app. When the app regains foreground it calls didChangeMetrics and that's where context is null. It made no difference using `ResponsiveWrapper` or `ResponsiveWrapper.builder`.

**Comment by searchy2** [comment]
Oh wow, glad you were able to reproduce. Is the solution to change from MediaQuery.of to MediaQuery.maybeOf?

**Comment by SpencerLindemuth** [comment]
I'm working on a solution, I'll iron it out and make a pull request tomorrow!

**Comment by searchy2** [comment]
Thank you for your help. Merged and released in v0.0.12

**Comment by searchy2** [comment]
Can this issue be closed?

**Comment by SpencerLindemuth** [comment]
Yes sorry, closing now!
