### ISSUE TITLE
DropdownButton  is not working

### ISSUE THREAD

**Issue by pesutsoos** [Codelessly/ResponsiveFramework#3]
If I use **ResponsiveWrapper.builder** it brakes my **DropdownButton**.

``runApp(MaterialApp(
    debugShowCheckedModeBanner: false,
    builder: (context, widget) =>
        ResponsiveWrapper.builder(TabsPage(),
            maxWidth: 1200,
            minWidth: 450,
            defaultScale: true,
            breakpoints: [
              ResponsiveBreakpoint(breakpoint: 450, name: MOBILE),
              ResponsiveBreakpoint(
                breakpoint: 800, name: TABLET, autoScale: true,),
              ResponsiveBreakpoint(
                  breakpoint: 1000, name: TABLET, autoScale: true),
              ResponsiveBreakpoint(breakpoint: 1200, name: DESKTOP),
              ResponsiveBreakpoint(
                  breakpoint: 2460, name: "4K", autoScale: true),
            ],
            background: Container(color: Color(0xFFF5F5F5))),

**Comment by searchy2** [comment]
Thanks for reporting this issue. Can you provide a sample code of your dropdown button? 
There are a few known issues with modals and routes that are on the roadmap to fix. Going to add dropdowns to the list too.

**Comment by KonsistentApps** [comment]
Hi @pesutsoos 

Maybe it will work with the following code:

``runApp(MaterialApp(
debugShowCheckedModeBanner: false,
builder: (context, widget) =>
ResponsiveWrapper.builder(
maxWidth: 1200,
minWidth: 450,
defaultScale: true,
breakpoints: [
ResponsiveBreakpoint(breakpoint: 450, name: MOBILE),
ResponsiveBreakpoint(
breakpoint: 800, name: TABLET, autoScale: true,),
ResponsiveBreakpoint(
breakpoint: 1000, name: TABLET, autoScale: true),
ResponsiveBreakpoint(breakpoint: 1200, name: DESKTOP),
ResponsiveBreakpoint(
breakpoint: 2460, name: "4K", autoScale: true),
],
background: Container(color: Color(0xFFF5F5F5))),
home: TabsPage(),

**Comment by searchy2** [comment]
I've done a bit of research into Overlays and there's hope for a good solution.
