### ISSUE TITLE
convex_bottom_bar 2.6.0 display issue

### ISSUE THREAD

**Issue by jdewolf621** [Codelessly/ResponsiveFramework#34]
Leveraging the ResponsiveFramework for an app I'm building. I'm having an issue where the botton nav bar (convex_bottom_bar) gets cut off on both sides on the screen.  If I remove the convex_bottom_bar and replace it with a blue container, it goes the full width of the screen.  Didn't know if others were having a similar issue?  Thanks!

![capture2](https://user-images.githubusercontent.com/67004344/101552749-626ff180-3981-11eb-8a42-3f9a4da4487b.png)

<img width="203" alt="Capture1" src="https://user-images.githubusercontent.com/67004344/101552801-77e51b80-3981-11eb-846b-f8bca4cb6ce0.PNG">

**Comment by searchy2** [comment]
Can you share a reproducible example with the convex_bottom_bar?

**Comment by jdewolf621** [comment]
This ended up being a issue with the way the app was constructed.  There were two material apps...one for the splash screen portion of the app and another for the rest of the app.  As soon as this issue was addressed, the formatting issue was corrected.

**Comment by searchy2** [comment]
Wonderful, glad you were able to resolve the issue.
