### ISSUE TITLE
Landscape mode and responsive framework

### ISSUE THREAD

**Issue by prateekmedia** [Codelessly/ResponsiveFramework#38]
### *Intro*
This framework works flawlessly for small screen devices, but when you turn your device into landscape mode the situation also becomes upside down.

### The Problem
Although this is able to hand my approximately 450x850 mobile, but when I turn it in landscape mode then all the ui elements are too big and some are even overflowing cause of the less dpi in small screen but that's not the case in portrait mode.

You can also try this on the [recreated flutter website](https://gallery.codelessly.com/flutterwebsites/flutterwebsite/?utm_medium=link&utm_campaign=demo), when you turn your phone with any resolution into landscape mode then everything becomes too big to handle event the bottomNavigationBar also doesnt respect the small screen.

It seems like it doesn't respect nor recognize small screens in landscape mode cause it thinks that the width is higher so that is true in landscape but it should also consider that the height is low in landscape mode cause the resolution becomes 850x450(in my small screen case)

### *Suggestion / Possible Solution*
Give us the option to specify other properties for landscape mode or by default respect landscape mode cause even if the width is high in it but the height is very low in that mode, or it should understand landscape mode by itself by checking the aspect ratio which is my case is approx 2:1 in landscape mode.

### *Enough Talk, Show me your code*
This is the code of my builder inside MaterialApp
```
builder: (context, widget) => ResponsiveWrapper.builder(
  BouncingScrollWrapper.builder(context, widget),
  minWidth: 450,
  defaultScale: true,
  breakpoints: [
    ResponsiveBreakpoint.resize(500, name: MOBILE),
    ResponsiveBreakpoint.autoScale(800, name: TABLET),
    ResponsiveBreakpoint.autoScale(1000, name: TABLET),
    ResponsiveBreakpoint.resize(1200, name: DESKTOP),
    ResponsiveBreakpoint.autoScale(2460, name: "4K"),
  ],
),
```

**Comment by searchy2** [comment]
Great issue. Thanks for providing a good explanation. I think I understand what you're saying but if you could provide some images of layouts that don't look right in landscape mode, that'd be great. 

Thanks for using this library!

**Comment by prateekmedia** [comment]
> Great issue. Thanks for providing a good explanation. I think I understand what you're saying but if you could provide some images of layouts that don't look right in landscape mode, that'd be great.
> 
> Thanks for using this library!

Ok let me capture the issue

**Comment by prateekmedia** [comment]
@searchy2 

**Portrait**
![IMG_20210124_105054](https://user-images.githubusercontent.com/41370460/105621898-61f8c080-5e32-11eb-9f46-aa804e2bb8a9.jpg)

**Landscape**
![IMG_20210124_105110](https://user-images.githubusercontent.com/41370460/105621901-67eea180-5e32-11eb-80e9-a3c74ec1832e.jpg)

Although it fits in landscape in my other 1280x720 mobile and other tablet but the 450x850 mobile doesn't fits it well.

**Comment by searchy2** [comment]
Thanks, I will take a look and add a landscape param most likely.

For now, can you take a look at ResponsiveRowColumn to see if it suits your needs?

**Comment by prateekmedia** [comment]
> For now, can you take a look at ResponsiveRowColumn to see if it suits your needs?

Thanks for the info about ResponsiveRowColumn, previously I was using a Similar setup as a widget cause their is not much info about this in the READme.

But this also doesn't do much and the problem still remains.. :(,

I hope this gets solved soon till then I am attaching the code of my responsive builder below:

```
builder: (context, widget) => ResponsiveWrapper.builder(
  BouncingScrollWrapper.builder(context, widget),
  minWidth: 450,
  defaultScale: true,
  breakpoints: [
    ResponsiveBreakpoint.resize(500, name: MOBILE),
    ResponsiveBreakpoint.autoScale(800, name: TABLET),
    ResponsiveBreakpoint.autoScale(1000, name: TABLET),
    ResponsiveBreakpoint.resize(1200, name: DESKTOP),
    ResponsiveBreakpoint.autoScale(2460, name: "4K"),
  ],
),
```

**Comment by searchy2** [comment]
Will create a fix for this issue soon.

**Comment by searchy2** [comment]
Good news! MediaQuery contains the landscape and portrait orientation property.

> MediaQuery.of(context).orientation
https://api.flutter.dev/flutter/widgets/MediaQueryData/orientation.html

**Comment by prateekmedia** [comment]
> Good news! MediaQuery contains the landscape and portrait orientation property.
> 
> > MediaQuery.of(context).orientation
> > https://api.flutter.dev/flutter/widgets/MediaQueryData/orientation.html
> 
> The ResponsiveFramework resolves the correct values to MediaQuery so you can confidently use that property.

Can you elaborate more?

**Comment by searchy2** [comment]
If you use MediaQueryData's orientation property, you will get Orientation.landscape and Orientation.portrait which is what you wanted right?

**Comment by prateekmedia** [comment]
Hey @searchy2,

Sorry for late reply, that's not what I wanted.

If you read my problem again then it when I set the breakpoints of responsive framework then it treats like 450x850(widthxheight) in portrait but in landscape it will become 850x450 so the breakpoints will think its a Tablet and will not apply the responsive breakpoint formula (hence some of my objects will come out of the screen as I reported in start of this issue), Code reference below

```
builder: (context, widget) => ResponsiveWrapper.builder(
  ...
  breakpoints: [
    ResponsiveBreakpoint.resize(500, name: MOBILE),  // my 450x850 mobile will behave as a mobile in portrait
    ResponsiveBreakpoint.autoScale(800, name: TABLET), // same 450x850 mobile will behave as a tablet \
        in landscape as in this mode width and height are switched(850x450),
    ...
  ],
),
```

I hope you can understand the underlying issue, It is not doing what it should do i.e. become responsive on all form factors and orientations.

Regards Prateek.

**Comment by searchy2** [comment]
My apologies, I thought I reopened this issue already.

**Comment by fdarsot** [comment]
@searchy2 
I also have the same issue. when turning my devices into landscape mode, the responsiveness is not working (everything is not fitting the screen properly). Any idea when a fix will be out?

**Comment by searchy2** [comment]
This'll be the next thing I look at.

**Comment by HasanMuslemani** [comment]
@searchy2 Any timeline for the fix?

**Comment by searchy2** [comment]
Not at the current time. This is an involved issue that needs quite a bit of thought to fix.

Do you have any suggestions?

**Comment by HasanMuslemani** [comment]
@searchy2 Are you using MediaQuery.of(context).size.width to determine the width? If so, you could change that to MediaQuery.of(context).size.shortestSide which will ensure the width is never changing even if they switch to landscape.

**Comment by searchy2** [comment]
I am not. That's a good suggestion, thank you!

**Comment by fdarsot** [comment]
Any timeline for a fix @searchy2 ?

**Comment by fdarsot** [comment]
? @searchy2

**Comment by searchy2** [comment]
Thank you for the experiments and additional information. 
I think I have the info I need to create a solution.

I can probably release a new version this week if everyone in this thread is willing to help me test.

**Comment by fdarsot** [comment]
@searchy2 sure! eagerly awaiting the release!

**Comment by fdarsot** [comment]
@searchy2 any luck?

**Comment by fdarsot** [comment]
@searchy2 ??

**Comment by marchellodev** [comment]
@searchy2 If you don't have the time to fix this, could you please tell us what is the proper way to do it, so that we can submit a PR?

**Comment by fdarsot** [comment]
@searchy2 my team and i are getting close to launch and this is one of the few missing pieces. please update when you can.

**Comment by searchy2** [comment]
My apologies, the solution here is to add a landscape breakpoints param and switch based on the media query returned orientation value.

I don't have time today but I'll try this weekend.

**Comment by searchy2** [comment]
Good news, I've added support for landscape breakpoints with the v0.1.1 release! 

Landscape mode support was as extensive as I imagined and really needed a good think through. 
The crux of the issue is that Flutter has no REAL landscape mode detection. The `orientation` is virtually computed based on if width > height. This means that landscape mode makes no sense on desktop or web. By default, the ResponsiveFramework only applies landscape breakpoints on iOS, Android, and Fuchsia. However, to keep things customizable, the supported landscape platforms can be customized by passing a list of supported platforms to `landscapePlatforms`.

Please test and let me know your thoughts and suggestions.

This is not full landscape support as it is missing minWidthLandscape, maxWidthLandscape, defaultScaleLandscape, defaultScaleFactorLandscape, etc. Any help adding support for those features is appreciated!

**Comment by fdarsot** [comment]
i think the issue still exists? i entered the following

 landscapePlatforms: [
            TargetPlatform.android,
            TargetPlatform.iOS,
          ],
          landscapeBreakpoints: [
            ResponsiveBreakpoint.autoScaleDown(450,
                name: MOBILE, scaleFactor: 0.73),
            ResponsiveBreakpoint.autoScaleDown(800,
                name: TABLET, scaleFactor: 0.73),
            ResponsiveBreakpoint.autoScaleDown(1000,
                name: TABLET, scaleFactor: 0.73),
            ResponsiveBreakpoint.autoScaleDown(1200,
                name: DESKTOP, scaleFactor: 0.73),
            ResponsiveBreakpoint.autoScaleDown(2460,
                name: "4K", scaleFactor: 0.73),
          ],

and it's still not working when i switch from portrait to landscape


anyone else?
@searchy2

**Comment by HasanMuslemani** [comment]
@fdarsot I could be wrong here but wouldn't the width change when in landscape so I don't think it'd be the same breakpoint numbers as portrait.

**Comment by fdarsot** [comment]
ohhh good point. i think you are correct @HasanMuslemani i was going based on the example in the repo. let me try new breakpoints

**Comment by fdarsot** [comment]
tried with different breakpoints, it still isnt working

**Comment by fdarsot** [comment]
is it working for anyone else?

**Comment by prateekmedia** [comment]
> is it working for anyone else?

What are your new breakpoints?

**Comment by fdarsot** [comment]
@prateekmedia i checked what my screen width was when it was in landscape mode and adjusted it to that.

landscapePlatforms: [
TargetPlatform.android,
TargetPlatform.iOS,
],
landscapeBreakpoints: [
ResponsiveBreakpoint.autoScaleDown(640,
name: MOBILE, scaleFactor: 0.73)
],

**Comment by searchy2** [comment]
Hmmm.. I'll find out the issue with some tests. 

For now, you need to test on a target device in order to have landscape apply. 

Landscape mode isn't enabled by default on Web or Desktop. 
You CAN enable it by adding windows, web, or macOS into the landscapePlatforms.

**Comment by fdarsot** [comment]
@searchy2 im testing on a real device with targeted breakpoints

im only developing for Android and IOS btw

**Comment by searchy2** [comment]
Well, that's unfortunate. 

I'll take a look tomorrow, the bulk of the work is done so it's probably a quick fix. 

And can add some tests!

**Comment by fdarsot** [comment]
Thank you for all your work btw! i think we're close. this is one of the few last things needed before we launch and it would be great to have.

**Comment by marchellodev** [comment]
I believe the problem is that flutter does not trigger `MaterialApp.builder` when orientation changes

**Comment by searchy2** [comment]
@fdarsot @prateekmedia 
v0.1.2 Released! 
- Full support for `landscapeBreakpoints` - breakpoints in landscape mode. Create landscape overrides with `minWidthLandscape`, `maxWidthLandscape`, `defaultScaleLandscape`, etc.
- Use `ResponsiveTargetPlatform` to enable landscape support for platforms including web.

I've verified through tests that landscape mode now works correctly. 
Please note that landscape can be VERY confusing, especially when testing on desktop or web. 

To test on desktop or web:
1. Add `ResponsiveTargetPlatform.windows` or the test platform to `landscapePlatforms`
2. Add landscape breakpoints to `breakpointsLandscape`.
3. Shrink the window height to something small like 200px. If the height is too large such as 600px, any width smaller than 600px activates portrait mode instead of landscape.
4. Check the `maxWidth`, `minWidth`, etc settings. You must override them with `maxWidthLandscape` if you want to use different values in landscape mode. Otherwise, the values default to the portrait values. 

Please test and hopefully everyone's issues are resolved.

**Comment by searchy2** [comment]
In spite of the seemingly complex concepts here, landscape and portrait breakpoints switch seemlessly and it's a beauty to behold.

**Comment by prateekmedia** [comment]
> In spite of the seemingly complex concepts here, landscape and portrait breakpoints switch seemlessly and it's a beauty to behold.

Ok looks great, although I will test it when I'm free. If anyone has any query then I will reopen it.

**Comment by marchellodev** [comment]
@elvosparsley You need to specify different breakpoints for both `breakpoints` and `breakpointsLandscape`. 

Here's how I am doing it in my app: https://github.com/marchellodev/sharik/blob/master/lib/main.dart#L63

**Comment by prateekmedia** [comment]
Closing again as issue is answered.

**Comment by elvosparsley** [comment]
> @elvosparsley You need to specify different breakpoints for both `breakpoints` and `breakpointsLandscape`.
> 
> Here's how I am doing it in my app: https://github.com/marchellodev/sharik/blob/master/lib/main.dart#L63

Many thanks for the example, I was missing the scaleFactor in the breakpoints, works great now!

**Comment by gOzaru** [comment]
I think if you want to get the best result of landscape mode, use this website's information about the resolution of devices you are targeting with: [click this link](https://www.binvisions.com/articles/tablet-smartphone-resolutions-screen-size-list/) 
You can see the list that the most wide device has resolution of 3120 pixel. 
This is the complete list for all the tablet with landscape mode:
768, 800, 1024, 1280, 2048, 2732

But on smartphone list, the width of all devices are all started with: 
640, 800, 960, 1136, 1334, 1440, 1920, 2340, 2560, 3040, 3120

So, I think you have to combine the both lists into like this:
640, 768, 800, 960, 1024, 1136, 1280, 1334, 1440 , 1920, 2048, 2340, 2560, 2732, 3040, 3120

You need to compare the list data against your testing device. 
For example, 
If my testing device is smartphone with resolution: 720 x 1440 
Then the width is 720 and the height is 1440. 
Your current width on device (720) will become the `minWidth` and current height (1440) will be come `minWidthLandscape`. You don't have to specify its name whether it is TABLET or MOBILE. You just need to count the `scaleFactor` value against the `minWidth` and `minWidthLandscape`. Like this code below:

```dart
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      builder: (context, child) {
        return ResponsiveWrapper.builder(
          BouncingScrollWrapper.builder(context, child!),
          minWidth: 720,
          maxWidth: 3120,
          defaultScale: true,
          landscapePlatforms: [ResponsiveTargetPlatform.android, ResponsiveTargetPlatform.iOS],
          breakpoints: [
            const ResponsiveBreakpoint.autoScaleDown(640, scaleFactor: 0.89),
            const ResponsiveBreakpoint.autoScale(768, scaleFactor: 1.067),
            const ResponsiveBreakpoint.autoScale(800, scaleFactor: 1.11),
            const ResponsiveBreakpoint.autoScale(960, scaleFactor: 1.33),
            const ResponsiveBreakpoint.autoScale(1024, scaleFactor: 1.42),
            const ResponsiveBreakpoint.autoScale(1136, scaleFactor: 1.57),
            const ResponsiveBreakpoint.autoScale(1334, scaleFactor: 1.85),
            const ResponsiveBreakpoint.autoScale(1440, scaleFactor: 2),
            const ResponsiveBreakpoint.autoScale(1920, scaleFactor: 2.67),
            const ResponsiveBreakpoint.autoScale(2048, scaleFactor: 2.84),
            const ResponsiveBreakpoint.autoScale(2340, scaleFactor: 3.25),
            const ResponsiveBreakpoint.autoScale(2560, scaleFactor: 3.56),
            const ResponsiveBreakpoint.autoScale(2732, scaleFactor: 3.79),
            const ResponsiveBreakpoint.autoScale(3040, scaleFactor: 4.19),
            const ResponsiveBreakpoint.autoScale(3120, scaleFactor: 4.33),
          ],
          minWidthLandscape: 1440,
          maxWidthLandscape: 3120,
          defaultScaleLandscape: true,
          breakpointsLandscape: [
            const ResponsiveBreakpoint.autoScaleDown(640, scaleFactor: 0.44),
            const ResponsiveBreakpoint.autoScaleDown(720, scaleFactor: 0.5),
            const ResponsiveBreakpoint.autoScaleDown(768, scaleFactor: 0.53),
            const ResponsiveBreakpoint.autoScaleDown(800, scaleFactor: 0.55),
            const ResponsiveBreakpoint.autoScaleDown(960, scaleFactor: 0.67),
            const ResponsiveBreakpoint.autoScaleDown(1024, scaleFactor: 0.71),
            const ResponsiveBreakpoint.autoScaleDown(1136, scaleFactor: 0.78),
            const ResponsiveBreakpoint.autoScaleDown(1334, scaleFactor: 0.926),
            const ResponsiveBreakpoint.autoScale(1920, scaleFactor: 1.33),
            const ResponsiveBreakpoint.autoScale(2048, scaleFactor: 1.42),
            const ResponsiveBreakpoint.autoScale(2340, scaleFactor: 1.625),
            const ResponsiveBreakpoint.autoScale(2560, scaleFactor: 1.77),
            const ResponsiveBreakpoint.autoScale(2732, scaleFactor: 1.89),
            const ResponsiveBreakpoint.autoScale(3040, scaleFactor: 2.11),
            const ResponsiveBreakpoint.autoScale(3120, scaleFactor: 2.167),
          ],
          background: Container(color: const Color(0xFFF5F5F5)),
        );
      },
      initialRoute: Routes.home,
      onGenerateRoute: (RouteSettings settings) {
        return Routes.fadeThrough(settings, (context) {
          switch (settings.name) {
            case Routes.home:
              return const ListPage();
            case Routes.post:
              return const PostPage();
            case Routes.style:
              return const TypographyPage();
            default:
              return const SizedBox.shrink();
          }
        });
      },
      debugShowCheckedModeBanner: false,
    );
  }
```
 
I think that is the best solution for your case.
I hope I don't misunderstand the function I wrote above.
