### ISSUE TITLE
Hero-wrapped widget looks giant during transition

### ISSUE THREAD

**Issue by ppgcharge** [Codelessly/ResponsiveFramework#4]
`MaterialApp(

          builder: (context, widget) => ResponsiveWrapper.builder(
            widget,
            maxWidth: 1200,
            minWidth: 450,
            defaultScale: true,
            breakpoints: [
              ResponsiveBreakpoint(breakpoint: 450, name: MOBILE),
              ResponsiveBreakpoint(breakpoint: 800, name: TABLET),
              ResponsiveBreakpoint(breakpoint: 1000, name: TABLET),
              ResponsiveBreakpoint(breakpoint: 1200, name: DESKTOP),
              ResponsiveBreakpoint(breakpoint: 2460, name: "4K"),
            ],
            background: Container(color: Color(0xFFF5F5F5))),...
`

**Comment by searchy2** [comment]
Thank you for reporting. This is a known issue.

The fix is on the roadmap for v0.2.0.

**Comment by carlosfiori** [comment]
Hi, is the v0.2.0 ready for update on pub.dev?
I'm facing the same issue with Hero animations

**Comment by searchy2** [comment]
Would you be interested in helping contribute a fix? I can point you in the right direction.

**Comment by carlosfiori** [comment]
Absolutely

**Comment by carlosfiori** [comment]
Hello happy new year.

I managed to discover that the problem is in the overlay created by Hero, I can't see a solution through the package itself, I think that for correction we will have to extend the original Hero and integrate the part that creates the overlay with the package, thus creating a new one hero that respects the defined scales.

**Comment by afnx** [comment]
@searchy2, I have the same problem. Have you found any workarounds so far?

Btw, I'd like to work on this If you can tell me from where I should start.

**Comment by searchy2** [comment]
@afnx Alois Deniel has solved some of the hero and drag target issues in his device preview.
If you can find his method, we might be able to integrate it into the Responsive Framework.

**Comment by carlosfiori** [comment]
As a workaround I've been using the package animations (https://pub.dev/packages/animations#container-transform), he gives a similiar animation.

**Comment by seyedmohammadali** [comment]
I have the same problem in Hero transition . can you help me bro ?
