### ISSUE TITLE
Migrate to Null Safety

### ISSUE THREAD

**Issue by pedromassango** [Codelessly/ResponsiveFramework#42]
Now that Null Safety is about to become stable it is important to have this package migrated as well or at least have a null safety version.

**Comment by searchy2** [comment]
Yes, this package will be migrated to null safety. 
There should be a tool released at Flutter Engage to help so I'm waiting on that.

**Comment by Eroo36** [comment]
Is there an update on this? Now its out but cannot migrate because apparently this package is not migrated to it yet

**Comment by bounty1342** [comment]
@Eroo36 : You will have to wait a bit or PR the migration yourself maybe ? 
No need to be rude or pushy. If I was the author, with comment like this, I would delay the release even further...

**Comment by searchy2** [comment]
Package will be migrated soon. Maybe even tonight.
We will want to do a preview release and bundle some breaking changes into v0.0.20 before a general release however.

That and testing by upgrading the test apps.

**Comment by searchy2** [comment]
There's now the nullsafety branch https://github.com/Codelessly/ResponsiveFramework/tree/nullsafety
Conversion is done but a there's a lot of testing before I'm confident in releasing. 
Would appreciate any help reviewing the code.

**Comment by pedromassango** [comment]
> Would appreciate any help reviewing the code.

@searchy2 we may need the PR for the review

**Comment by searchy2** [comment]
Oh right! https://github.com/Codelessly/ResponsiveFramework/pull/45

**Comment by searchy2** [comment]
Please look over the PR if any of you have time.

**Comment by searchy2** [comment]
Null Safety release :tada: https://github.com/Codelessly/ResponsiveFramework/releases/tag/0.1.0
