### ISSUE TITLE
Cannot use GetX context

### ISSUE THREAD

**Issue by bagaswastu** [Codelessly/ResponsiveFramework#44]
When I use responsive framework I can't use [getx](https://github.com/jonataslaw/getx) context, whenever I called context with getx the context is always null.

How to produce:
- Install getx package
- use function that requires context, for example: `Get.to(Homepage())`

**Comment by searchy2** [comment]
Thank you for reporting, this definitely shouldn't be the case so let me look into it.

**Comment by searchy2** [comment]
Can you try the following configuration? GetX worked for me when using the builder property. 
![MaxthonSnap20210302221708](https://user-images.githubusercontent.com/19896174/109751915-13fb7900-7ba5-11eb-9517-7e1f5a60cf9d.png)

**Comment by searchy2** [comment]
Was my answer helpful in resolving your issue?

**Comment by bagaswastu** [comment]
Hi, sorry for late response, your code works like a charm, thank you!
