### ISSUE TITLE
Bottom overflowed issue

### ISSUE THREAD

**Issue by Jumon7** [Codelessly/ResponsiveFramework#48]
I have tried the framework and works fine in portrait mode but when I make it landscape mode problem occurs, In my 5.9" phone screen when I try to show a dialog it shows bottom overflowed by.... pixels. 
what can be probable solution to it?
Texts also seems appears smaller than expected. 
Im using this sizing.

 builder: (context,widget) => ResponsiveWrapper.builder(
        BouncingScrollWrapper.builder(context, widget),
          maxWidth: 1200,
          minWidth: 480,
          defaultScale: true,
          breakpoints: [
            ResponsiveBreakpoint.resize(480, name: MOBILE),
            ResponsiveBreakpoint.autoScale(800, name: TABLET),
            ResponsiveBreakpoint.resize(1000, name: DESKTOP),
          ],
          background: Container(color: Color(0xFFF5F5F5)),

      ),

![framework prob](https://user-images.githubusercontent.com/44614230/111467371-a878e600-8724-11eb-97fa-16712f5f1a52.jpg)

Thanks in advance :)

**Comment by bounty1342** [comment]
When you go landscape, you certainly trigger ResponsiveBreakpoint.resize(1000, name: DESKTOP),

The proportions will change (space taken by the text), so you need to use those flexible and expand to protect your column and row from overflowing.
Or you could only use scale only and remove those resize breakpoint. (but on large device, it might look a bit/lot bulky)
