### ISSUE TITLE
What is the issue with traditional breakpoints?

### ISSUE THREAD

**Issue by searchy2** [Codelessly/ResponsiveFramework#5]
Webflow added 3 new breakpoint layouts for a total of 7. Now users have the joy of creating and maintaining 7 layouts 😧
![MaxthonSnap20200410100742](https://user-images.githubusercontent.com/19896174/79005592-d325ec00-7b1c-11ea-8824-63e38881f412.png)

**Comment by ripern** [comment]
Is this a bug or a feature or something else? A bit misleading title?
Are you planning to add support for those 3 extra breakpoints that Webflow added?

**Comment by searchy2** [comment]
The problem with how Webflow does responsiveness is that every breakpoint requires recreating the same layout again. With the addition of 3 new breakpoints, Webflow users can now recreate the same layout 7 times instead of 4.
