### ISSUE TITLE
The responsive framework is not scaling on a particular device

### ISSUE THREAD

**Issue by naveenbharadwaj19** [Codelessly/ResponsiveFramework#53]
```
builder : (context, widget) => ResponsiveWrapper.builder(
          // ? warp all the heights and widths according to screen automatically
          widget,
          defaultScale: true,
          breakpoints: [
            ResponsiveBreakpoint.autoScale(420, name: MOBILE), //  breakpoint is set based on pixel 2 dpi
          ],
          backgroundColor: Theme.of(context).primaryColor,
        ),
// nested widgets ....
```
`flutter mode : release`

autoscale should render the same UI on all the devices right ? but why oneplus 6 differs from other devices am i doing anything wrong ?

**Images :**

UI in **oneplus 6** :
![1+6 (2)](https://user-images.githubusercontent.com/63662884/115693137-46dc1500-a37d-11eb-982d-cee00b46de50.jpg)
![1+6 (3)](https://user-images.githubusercontent.com/63662884/115693140-480d4200-a37d-11eb-99dd-2af95aaef42e.jpg)
![1+6](https://user-images.githubusercontent.com/63662884/115693141-48a5d880-a37d-11eb-9b4d-e5b522af1f7f.jpg)

UI in rest of the device like **pixel2,oneplus 5t , vivo9 , pixel4 ..** :
![1+5t (2)](https://user-images.githubusercontent.com/63662884/115694227-4b54fd80-a37e-11eb-859b-b7a078a35988.jpg)
![1+5t (3)](https://user-images.githubusercontent.com/63662884/115694235-4c862a80-a37e-11eb-950a-0e4a59036e52.jpg)
![1+5t](https://user-images.githubusercontent.com/63662884/115694238-4c862a80-a37e-11eb-8c8a-79295a078f8f.jpg)

**Comment by searchy2** [comment]
Good question! I have the OnePlus 6 device so lucky us.
Can you share a complete reproduceable code sample?
