### ISSUE TITLE
Alignment of ResponsiveWrapper not working

### ISSUE THREAD

**Issue by apalala-dev** [Codelessly/ResponsiveFramework#54]
Hello,

Alignment parameter doesn't seem to have any effect for me.
This is a sample to reproduce the problem:

``` dart
class SampleNotWorking extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
        color: Colors.green,
        child: ResponsiveWrapper.builder(
            Container(
                width: MediaQuery.of(context).size.width,
                height: MediaQuery.of(context).size.height - 200,
                color: Colors.red),
            alignment: Alignment.bottomCenter));
  }
}
```

I would expect the red box to be aligned at the bottom center (I also tried with other values with no luck) but it is always centered instead:

![image](https://user-images.githubusercontent.com/6177464/119957742-a643cb00-bfa2-11eb-94c3-f1d6fb324bb9.png)

**Comment by searchy2** [comment]
Thank you for filing this issue. I don't know what the issue is off the top of my head and will take a look next week.
