### ISSUE TITLE
Difference between this package and flutter_screenutil?

### ISSUE THREAD

**Issue by alvindrakes** [Codelessly/ResponsiveFramework#58]
Hi codelesssly, I just stumbled upon your package and I am wondering what's the difference between this package and https://pub.dev/packages/flutter_screenutil

Are there any fundamental differences in the way these 2 packages calculate the scaling? 

Any explanations are appreciated. 
Thank you.

**Comment by searchy2** [comment]
Hi Alvin, the packages share fundamentally different philosophies. 

The entire purpose of the ResponsiveFramework is to eliminate the need for widget level responsive development as much as possible. What that means is that you define your breakpoints in the ResponsiveFramework at the top level and then control the behavior from those breakpoints. 

This approach works very well for building websites. I recommend checking out the example apps! 

Also, as of v0.1.4, this is the only library that handles multiplatform landscape mode correctly.

**Comment by alvindrakes** [comment]
Thanks for the quick reply!  

I've checked the example website and have 1 more question as I'm not a ui designer. 

Do we always **scale** for website and **resize** for mobile? Is the setup in the example app the standard? 

What happened if I use **Scale** on mobile and not **resize**? 

Basically I'm trying to get the right ui responsive behaviour for mobile and web.
