### ISSUE TITLE
OS specific Alert Dialogs shrinking.

### ISSUE THREAD

**Issue by andrespd99** [Codelessly/ResponsiveFramework#60]
I have noticed that the Responsive Framework is shrinking the Cupertino Alert Dialog more than usual, making the UI feel off from iOS standards. Is there any workaround?

**Comment by andrespd99** [comment]
Ok, so to give a clear example of what I'm talking about, here are two screenshots. The first is using te responsive_framework package. The second is how it SHOULD look. 

This might be a minimal issue but it is a real dealbreaker for me because it breaks the "iOS standard style" to give it a name. 

Is there any way I can stop this from happening?
 
![image](https://user-images.githubusercontent.com/39571970/126908868-6b596631-20ae-4647-9618-fce83cd7cfc8.png)
![image](https://user-images.githubusercontent.com/39571970/126908877-2748b053-2446-4206-8416-678d74df14d6.png)

**Comment by searchy2** [comment]
Hmmm, this is on the v0.2.0 release roadmap. 

Any ideas how to fix the issue?
