### ISSUE TITLE
Doesn't work in conjunction with device_preview library

### ISSUE THREAD

**Issue by MenaRaafat** [Codelessly/ResponsiveFramework#62]
Using Responsive Framework alongside device_preview library produces a distorted UI. 

Device_preview library:
https://pub.dev/packages/device_preview

```

void main() {
  // runApp(DevicePreview(
  //     enabled: true, //!kReleaseMode,
  //     plugins: [
  //       const ScreenshotPlugin(),
  //       const FileExplorerPlugin(),
  //       const SharedPreferencesExplorerPlugin(),
  //     ],
  //     builder: (context) => MyApp()));

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Sizer(
      builder: (context, orientation, deviceType) {
        return MaterialApp(
          debugShowCheckedModeBanner: false,
          title: "MyAppTitle",
          color: Colors.yellow,
          home: Home(),
          builder: (context, widget) => ResponsiveWrapper.builder(
            BouncingScrollWrapper.builder(context, widget!),
            maxWidth: 2060,
            minWidth: 450,
            defaultScale: true,
            breakpoints: [
              ResponsiveBreakpoint.resize(450, name: MOBILE),
              ResponsiveBreakpoint.autoScale(800, name: TABLET),
              ResponsiveBreakpoint.autoScale(1000, name: TABLET),
            //  ResponsiveBreakpoint.resize(1200, name: DESKTOP),
            //  ResponsiveBreakpoint.autoScale(2460, name: "4K"),
            ],
          ),
        );
      },
    );
  }
}
```

**Comment by searchy2** [comment]
Uh oh, that's not good. 
This library was fully compatible with Device Preview. 

Can you share a screenshot of the distortion?

**Comment by MenaRaafat** [comment]
@searchy2 
Commenting Device_preview library:
![Screenshot_1627811501](https://user-images.githubusercontent.com/42410083/127766747-0d69b441-dba9-4d6e-a672-079e6a3cdaba.png)

Uncommenting Device_preview library:
![Screenshot_1627811405](https://user-images.githubusercontent.com/42410083/127766771-f642a318-9e04-4533-b2ff-e4e45fa4d769.png)

**Comment by Husssam12** [comment]
I have the same issue, I solved it by passing mediaQueryData to ResponsiveWrapper.builder

`  Widget build(BuildContext context) {
    return ResponsiveWrapper.builder(
      child,
      maxWidth: 1200,
      minWidth: 500,
      mediaQueryData: MediaQuery.of(context),
      defaultScale: true,
      breakpoints: [
        const ResponsiveBreakpoint.resize(450, name: MOBILE),
        const ResponsiveBreakpoint.autoScale(800, name: TABLET),
        const ResponsiveBreakpoint.resize(1000, name: DESKTOP),
      ],
    );
  }`

**Comment by felipecastrosales** [comment]
@searchy2 and @Codelessly news about this?
