### ISSUE TITLE
Widget not able to be changed once breakpoint is set

### ISSUE THREAD

**Issue by shahbazqa** [Codelessly/ResponsiveFramework#65]
Hi, 
First would like to say, thank you so much for this Responsive Framework. It has helped tremendously to make my app look scaled and beautiful. Second i am having trouble, all my UI is looking good when i do the 
  ResponsiveBreakpoint.resize(300, name: MOBILE, scaleFactor: 0.8),

However, my image keeps riding up and will not go down no matter what height or width i place within the code: 
  // child: AspectRatio(
                                // aspectRatio: 0.7,
                                // alignment: Alignment.center,
                                child: new Image.asset(widget.quranImagepgs,
                                    // width: 500,
                                    // height: 700,
                                    width: width * 1,
                                    height: height * .8,
                                    // fit: BoxFit.fitWidth,
                                    fit: BoxFit.fill),
is there a way around this..? Is there a way to have some widgets follow the responsive framework and the other widgets to be changed by code? 
I really need this, as one place it is looking great the other place is not looking great. 

thank you

**Comment by searchy2** [comment]
Would adding an ability to customize sizing per page be enough to resolve your issue?

**Comment by shahbazqa** [comment]
I think that should be good, would you be able to do that? 
Also can we have a video call please really need help with this framework...
