### ISSUE TITLE
size issues with flutter_native_splash plugin

### ISSUE THREAD

**Issue by mattjslaton** [Codelessly/ResponsiveFramework#66]
Plugin works great, one thing that I am kinda stumped on is the fact that it resizes the splash screen and then jumps to a bigger size that fits the screen correctly, is there a way to adjust this so it does not change the splash screen but everything else afterwards gets resized as it normally does with this plugin? Thanks

**Comment by searchy2** [comment]
Is the resize happening on Web? 
If so, that's a known Flutter issue.

**Comment by mattjslaton** [comment]
Yes, that is correct. I guess for now I will remove the splash. Thanks!
