### ISSUE TITLE
[Question] Knowing the current breakpoint

### ISSUE THREAD

**Issue by matthewrice345** [Codelessly/ResponsiveFramework#7]
It seems like all the decision making is made a or near the root of the app. How would I know the currently active breakpoint further down the widget tree to make a decision on how a child widget is laid out? 

Maybe this is more of a feature request? I know I can use my own tooling with Provider or something but seems like a tool that would be very useful to have baked in.

**Comment by searchy2** [comment]
Thanks for trying out the Responsive Framework. To answer your question, you can access `ResponsiveWrapper`'s internal data with `ResponsiveWrapper.of(context)`. 

I'll be adding more documentation in this regard for the v0.3.0 release. 

> all the decision making is made a or near the root of the app

Nice work identifying one of the core tenants of the Reponsive Framework ;) 
I want people to think about responsiveness in a top-down, layout-driven way.

**Comment by matthewrice345** [comment]
Thanks much and good work!

**Comment by jg-l** [comment]
> Thanks for trying out the Responsive Framework. To answer your question, you can access `ResponsiveWrapper`'s internal data with `ResponsiveWrapper.of(context)`. 
> 
> I'll be adding more documentation in this regard for the v0.3.0 release. 
> 
> > all the decision making is made a or near the root of the app
> 
> Nice work identifying one of the core tenants of the Reponsive Framework ;) 
> I want people to think about responsiveness in a top-down, layout-driven way. 

Can help with documentation! This package is great and needs more recognition

**Comment by searchy2** [comment]
@jg-l thanks for the offer to help with the documentation! Please email me at ray@codelessly.com and I can help you get started. 
Right now, I'm still working on finalizing the API for v0.1.0 so there's a lot to help with.
