### ISSUE TITLE
Possible to scale up while past maxSize?

### ISSUE THREAD

**Issue by rubenvereecken** [Codelessly/ResponsiveFramework#70]
Our use case is an app that runs in the browser. We don't want to make anything responsive yet, it should just be roughly the size of a phone on your desktop. We've got the following working brilliantly:

```dart
    return ResponsiveWrapper.builder(
      child,
      // If screen is smaller than this and scaling is enabled, it will paint it as if screen width
      // is `minWidth`, then scale everything down to fit the actual screen
      // NOTE this doesn't work if one of the breakpoints is less than `minWidth`
      minWidth: 480,
      // If screen is bigger than this, restricts the app to only use the middle portion of the screen
      // up to `maxWidth`
      maxWidth: 480,
      defaultScale: true,
      breakpoints: [
        const ResponsiveBreakpoint.resize(480, name: DESKTOP),
      ],
    );
```

What we'd like on top of this is the following. When the screen is bigger than `maxWidth`, all fonts should scale up. The reason behind this is that people are further away from bigger screens, so font size should grow too to make it easier on the eyes. Currently this is achieved by using a different theme depending on width. So the app will be the same width but if you make your screen bigger, the font size grows along with it in some fashion.

The only way I've been able to make the font size grow is by adding smaller break points that scale up. But no way as of yet to make it scale up when past `maxWidth`.

Is this possible using this package? Is this something you're interested in supporting?

**Comment by rubenvereecken** [comment]
I've managed a constant scale-up using the `scaleFactor` argument for breakpoints. This at least precludes the need for a second theme.

I'd still be curious for an answer to the original question because I think this is a really neat package.

**Comment by searchy2** [comment]
Good question! Is there a property to control maxWidth scale? If so, could that be used to control the scale above maxWidth?
