### ISSUE TITLE
Contribution for Documentation

### ISSUE THREAD

**Issue by DCKaLpEsH** [Codelessly/ResponsiveFramework#73]
@searchy2  I replied to you regarding the documentation on resocoder's youtube tutorial. Just to remind you regarding that. Will be waiting for your reply.

**Comment by searchy2** [comment]
Thank you, I'll add it today!

**Comment by DCKaLpEsH** [comment]
Check your Twitter DM's, I've messaged you there too. We can discuss about more things there in.
