### ISSUE TITLE
Scroll to textField doesn't work when using ResponsiveFramework

### ISSUE THREAD

**Issue by bonsoirelliot** [Codelessly/ResponsiveFramework#84]
Hello.  I use Scaffold's `resizeToAvoidBottomInset` to scroll to textField when click on it. I wrapped the content inside MaterialApp in the way it was said in the tutorial. And scroll to textFields stopped to work. Thank you

**Comment by searchy2** [comment]
Thanks for reporting. Can you please share a code sample?

**Comment by bonsoirelliot** [comment]
Sorry, There was MediaQuery above main screen. The problem was caused by it

**Comment by karimsayf** [comment]
this issue is stall facing me, the scrolling cannot work ever, how would I solve this? @searchy2 @bonsoirelliot
