### ISSUE TITLE
Max items in column before breaking to new row

### ISSUE THREAD

**Issue by jeremiahlukus** [Codelessly/ResponsiveFramework#87]
I want to be able to pass in maxItems in column then auto break to new row after the maxItems number is reached 

```dart
          ResponsiveRowColumn(
            rowMainAxisAlignment: MainAxisAlignment.center,
            rowPadding: const EdgeInsets.all(30),
            columnPadding: const EdgeInsets.all(30),
            layout: ResponsiveWrapper.of(context).isSmallerThan(DESKTOP)
                ? ResponsiveRowColumnType.COLUMN
                : ResponsiveRowColumnType.ROW,
            children: [
              ...buildDataTile(),
            ],
          ),
          
 ```
 
 buildDataTile returns a `List<ResponsiveRowColumnItem>` 's. How can I add a maxItems to the column?

**Comment by devDonald** [comment]
Please this wasn't answered. I am trying to arrange 2 items per row on mobile and 4 per row on tablet. But the default is 1 per item per row in mobile and it forces everything to fit into a row on tablet no matter the number of items

**Comment by devDonald** [comment]
@jeremiahlukus How did you solve this please

**Comment by searchy2** [comment]
I can add the ability to set max items as a new feature.

**Comment by devDonald** [comment]
> I can add the ability to set max items as a new feature.

Please do.

**Comment by jeremiahlukus** [comment]
@devDonald I did not solve it i just worked around it. Would be great to have this feature though @searchy2

**Comment by jeremiahlukus** [comment]
@searchy2  this is completed? What branch has this? I would definitely like to update to use this.
