### ISSUE TITLE
GridView.builder?

### ISSUE THREAD

**Issue by d-apps** [Codelessly/ResponsiveFramework#9]
What about GridView.builder that has **crossAxisCount** and **childAspectRatio**, how to control it using responsive_framework, does this plugin it in any way? Or do I need to check the size of width and height to set manually this values?

**Comment by searchy2** [comment]
Understanding the right approach to grids is something I have to think more about. I'm planning to add a portfolio layout to my Minimal template to test out some implementation methods. 

For now, you can calculate the width and heights manually. 
Here's an example of how you might configure the columns based on the breakpoint:

> DESKTOP - 3 columns
> TABLET - 2 columns
> MOBILE - 1 column

```dart
int columnCount = 3;
if (ResponsiveWrapper.of(context).equals(MOBILE) || ResponsiveWraper.of(context).isSmallerThan(MOBILE)) {
    // Set column count to 1 on MOBILE and smaller.
    columnCount = 1;
} else if (ResponsiveWrapper.of(context).equals(TABLET)) {
    // Set column count to 2 for tablet layouts.
    columnCount = 2;
} else {
    // For desktop and above, default columnCount to 3.
}
```

Hope this helps!

**Comment by searchy2** [comment]
Had a chance to play around with the GridView and am working through the different scenarios. It's an interesting challenge because GridView sizes it's children based on the screen width.

**Comment by searchy2** [comment]
GridView has responsiveness challenges so I've created a custom ResponsiveGridView. https://github.com/Codelessly/ResponsiveFramework/blob/master/lib/responsive_grid.dart

ResponsiveGridView enables greater item sizing control and when combined with ResponsiveValue or ResponsiveRowColumnItem, responsive layout control.
