### ISSUE TITLE
Not Detect Devide ZFold in and ZFold out 

### ISSUE THREAD

**Issue by duongkibo** [Codelessly/ResponsiveFramework#97]
Not Detect Devide ZFold in and ZFold out

**Comment by dipen-apptrait** [comment]
Hey Did you find any solution for this issue?

**Comment by gOzaru** [comment]
Yeah, I also have the same issue.
It had a very big scale, and the scaleFactor doesn't affect the scale at all.

![SS - Responsive Framework 04](https://user-images.githubusercontent.com/3258483/183362631-8dabaf81-d05f-4d93-a146-7c95fad1a8e1.jpg)

**Comment by duongkibo** [comment]
> Hey Did you find any solution for this issue?

I think detect size of zfold device and  change size if device is zfold
