### ISSUE TITLE
Material You Warning 

### ISSUE THREAD

**Issue by MezoPeeta** [Codelessly/ResponsiveFramework#98]
When I updated to flutter 3 , and started to use material you in my app , I got that warning from the framework so please update it as fast as possible , It's very important to me 
`/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.7/lib/responsive_wrapper.dart:623:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
`

**Comment by Prayer-RecycleSmart** [comment]
Done it but seems to have same issues

```../../../flutter/.pub-cache/hosted/pub.dartlang.org/responsive_framework-0.1.8/lib/responsive_wrapper.dart:645:29: Error: Method 'addPostFrameCallback' cannot be called on 'WidgetsBinding?' because it is potentially null.
[        ]  - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../flutter/packages/flutter/lib/src/widgets/binding.dart').
[        ] Try calling using ?. instead.
[        ]     WidgetsBinding.instance.addPostFrameCallback((_) ...```

**Comment by iPatel007** [comment]
I upgraded Flutter 3.0 and thought that issue because of latest Flutter version, So I downgraded Flutter version 2.10.5 but same issue facing! 😞

**Comment by flutterninja9** [comment]
I took the decision to not to migrate to Flutter 3, and removed caret(^) from pubspec.yaml,
change to: flutter_segment: 3.7.0

Hopefully will be migrating soon😅

**Comment by searchy2** [comment]
The warning does not prevent your app from compiling. 
Look at the very bottom of the unable to build stack trace for the real incompatibility. 

If you are using v0.1.8 of ResponsiveFramework, you should not see this warning.

**Comment by flutterninja9** [comment]
@searchy2 True, In my case it was 'getX'🥲

**Comment by Parul-kapoor** [comment]
Facing same issue with 0.1.8 as well.

Error: Method 'addObserver' cannot be called on 'WidgetsBinding?' because it is potentially null.

**Comment by searchy2** [comment]
Can you screenshot the error?

**Comment by iPatel007** [comment]
@searchy2 Sure pls look this screenshot.
![Screenshot 2022-05-18 at 3 48 30 PM](https://user-images.githubusercontent.com/3183449/169016879-41876735-c940-4301-b088-8473cc951656.png)

**Comment by searchy2** [comment]
Fixed with correct compatibility versions.
