### ISSUE TITLE
0.1.8 # Flutter 3 support.

### ISSUE THREAD

**Issue by haamaanaa** [Codelessly/ResponsiveFramework#99]
Should not release possible API breaking changes in patch version upgrades

automatic dependency updates that flutter offers take this update and causes apps to not build anymore

like:
responsive_framework: ^0.1.4 => uses 0.1.8 && breaks

**Comment by limitless-brain** [comment]
As a fix, you can use what flutter [suggest](https://docs.flutter.dev/development/tools/sdk/release-notes/release-notes-3.0.0#your-code) to support the older versions of flutter.

**Comment by searchy2** [comment]
You're right, I made a mistake here. Flutter's upgrade docs did not mention this breaking change.

I've released a v0.1.9 as a compatibility release for Flutter v2. 
For Flutter v3, please use v0.2.0. 

We live and learn!

**Comment by haamaanaa** [comment]
> You're right, I made a mistake here. Flutter's upgrade docs did not mention this breaking change.
> 
> I've released a v0.1.9 as a compatibility release for Flutter v2. For Flutter v3, please use v0.2.0.
> 
> We live and learn!

Thanks for the quick change / fix, Much appreciated!

Unfortunately after I checked how Flutter handles this dependency conflict resolution, that 0.2.0 still breaks app that use ^ notation :(

https://docs.flutter.dev/development/packages-and-plugins/using-package
<img width="735" alt="Screenshot 2022-05-19 at 9 47 30" src="https://user-images.githubusercontent.com/19222773/169228362-ac06e8ca-75b6-4061-990b-163576ef73de.png">
s

**Comment by searchy2** [comment]
Ah, good to know! 

Flutter v2 users will need to hardcode 0.1.9 then.

**Comment by searchy2** [comment]
Actually, because I've set the constraint to Flutter 3 for v0.2.0, version solving should automatically default to the right version. 
So someone using ^0.1.8 will get the correct version on Flutter 2 and 3.
